#!/usr/bin/env bash
# agnos-index generator (bash + POSIX awk): builds process/INDEX.idx.md.
# Implements RQ-IDX-001 to RQ-IDX-009, RQ-IDX-015, RQ-IDX-016 (ADR-IDX-001: DEC-IDX-001 to DEC-IDX-004).
# Output must stay byte-identical to build-index.ps1. No gawk extension, no regex interval {n}.
# Usage (from the repository root): bash .github/skills/agnos-index/scripts/build-index.sh
# Exit codes: 0 ok, 1 error (nothing written), 2 duplicate IDs (index written).
set -u
export LC_ALL=C

PROCESS_DIR="process"
INDEX_FILE="$PROCESS_DIR/INDEX.idx.md"
SCAN_DIRS="1.requirements 2.architecture 3.plan"

if [ ! -d "$PROCESS_DIR" ]; then
  echo "agnos-index: '$PROCESS_DIR' folder not found - run from the repository root" >&2
  exit 1
fi

# RQ-IDX-001: documents to index, in ordinal path order (RQ-IDX-005).
list_documents() {
  for d in $SCAN_DIRS; do
    if [ -d "$PROCESS_DIR/$d" ]; then
      find "$PROCESS_DIR/$d" -type f -iname '*.md' ! -iname '*.idx.md' ! -iname '*readme.md' ! -iname '*template.md'
    fi
  done | sort
}

tmp="$INDEX_FILE.tmp.$$"
counts=$(list_documents | awk -v out="$tmp" '
function trim(s) { sub(/^[ \t]+/, "", s); sub(/[ \t]+$/, "", s); return s }
# DEC-IDX-002: a heading of level L closes every open section of level >= L.
function close_sections(level, last) {
  while (depth > 0 && slevel[depth] >= level) { elast[sentry[depth]] = last; depth-- }
}
# RQ-IDX-004: first status field wins; "|" would break the row format.
function set_status(e, value) {
  if (!(e in hasstatus)) { hasstatus[e] = 1; value = trim(value); gsub(/\|/, "/", value); estatus[e] = value }
}
# RQ-IDX-002 to RQ-IDX-004, RQ-IDX-006, RQ-IDX-007: one pass per document.
function scan(f,   path, line, ln, infence, fchar, flen, marker, level, text, id, rest, awaiting, prefix, num) {
  path = docs[f]; gfirst[f] = ne + 1; depth = 0; infence = 0; awaiting = 0; ln = 0
  while ((getline line < path) > 0) {
    ln++
    sub(/\r$/, "", line)
    if (ln == 1) sub(/^\357\273\277/, "", line)
    if (infence) {
      if (line ~ /^[ \t]*(`+|~+)[ \t]*$/) {
        marker = trim(line)
        if (substr(marker, 1, 1) == fchar && length(marker) >= flen) infence = 0
      }
      continue
    }
    if (line ~ /^[ \t]*(```+|~~~+)/) {
      marker = line; sub(/^[ \t]+/, "", marker)
      fchar = substr(marker, 1, 1); flen = 0
      while (substr(marker, flen + 1, 1) == fchar) flen++
      infence = 1; awaiting = 0
      continue
    }
    if (match(line, /^#+/) && RLENGTH <= 6 && (length(line) == RLENGTH || substr(line, RLENGTH + 1, 1) ~ /[ \t]/)) {
      level = RLENGTH
      text = trim(substr(line, level + 1))
      awaiting = 0
      close_sections(level, ln - 1)
      if (match(text, /^(FTR|RQ|ADR|DEC|PLAN|TASK)-[A-Z][A-Z][A-Z]-[0-9][0-9][0-9]/)) {
        id = substr(text, 1, RLENGTH); rest = substr(text, RLENGTH + 1)
        if (rest == "" || rest ~ /^[ \t:]/) {
          rest = trim(rest)
          if (substr(rest, 1, 1) == ":") rest = trim(substr(rest, 2))
          ne++; eid[ne] = id; efirst[ne] = ln; estatus[ne] = ""; etitle[ne] = rest
          depth++; sentry[depth] = ne; slevel[depth] = level
          if (id in seen) { ndup++; dup[ndup] = "agnos-index: DUPLICATE " id " " path ":" ln " (first: " seen[id] ")" }
          else seen[id] = path ":" ln
          prefix = substr(id, 1, length(id) - 4); num = substr(id, length(id) - 2) + 0
          if (!(prefix in maxnum)) { norder++; order[norder] = prefix; maxnum[prefix] = num }
          else if (num > maxnum[prefix]) maxnum[prefix] = num
        }
      } else if (text == "Status" && depth > 0) awaiting = sentry[depth]
      continue
    }
    if (depth > 0 && match(line, /^[ \t]*([-*+][ \t]+)?\*\*Status\*\*[ \t]*:/)) {
      awaiting = 0
      set_status(sentry[depth], substr(line, RLENGTH + 1))
      continue
    }
    if (awaiting && line !~ /^[ \t]*$/) { set_status(awaiting, line); awaiting = 0 }
  }
  close(path)
  close_sections(0, ln)
  glast[f] = ne
}
$0 != "" { ndocs++; docs[ndocs] = $0 }
END {
  for (f = 1; f <= ndocs; f++) scan(f)
  # RQ-IDX-005, RQ-IDX-006: index layout.
  print "# AGNOS process index - GENERATED by the agnos-index skill, never edit by hand." > out
  print "# \"@<path>\" opens a document; rows: ID|first-last|status|title" > out
  s = "#next"
  for (i = 1; i <= norder; i++) s = s " " order[i] "-" sprintf("%03d", maxnum[order[i]] + 1)
  print s > out
  for (f = 1; f <= ndocs; f++) {
    print "@" docs[f] > out
    for (e = gfirst[f]; e <= glast[f]; e++) print eid[e] "|" efirst[e] "-" elast[e] "|" estatus[e] "|" etitle[e] > out
  }
  close(out)
  for (i = 1; i <= ndup; i++) print dup[i] > "/dev/stderr"
  printf "%d entries, %d documents", ne, ndocs
  exit (ndup > 0 ? 2 : 0)
}')
status=$?

if [ "$status" -ne 0 ] && [ "$status" -ne 2 ]; then
  rm -f "$tmp"
  exit 1
fi

# RQ-IDX-009: rewrite only on change.
if [ -f "$INDEX_FILE" ] && cmp -s "$tmp" "$INDEX_FILE"; then
  rm -f "$tmp"
  state="unchanged"
else
  mv "$tmp" "$INDEX_FILE"
  state="updated"
fi

echo "agnos-index: $counts, $INDEX_FILE $state"
exit "$status"
