# agnos-index generator (Windows PowerShell 5.1): builds process/INDEX.idx.md.
# Implements RQ-IDX-001 to RQ-IDX-009, RQ-IDX-015, RQ-IDX-016 (ADR-IDX-001: DEC-IDX-001 to DEC-IDX-004).
# Output must stay byte-identical to build-index.sh. Keep this file ASCII-only (PowerShell 5.1).
# Usage (from the repository root): powershell -NoProfile -File .github/skills/agnos-index/scripts/build-index.ps1
# Exit codes: 0 ok, 1 error (nothing written), 2 duplicate IDs (index written).
$ErrorActionPreference = 'Stop'

$ProcessDir = 'process'
$IndexFile = 'process/INDEX.idx.md'
$ScanDirs = @('1.requirements', '2.architecture', '3.plan')
$IncludeRx = '\.md$'
$ExcludeRx = '(\.idx\.md|readme\.md|template\.md)$'
$Header1 = '# AGNOS process index - GENERATED by the agnos-index skill, never edit by hand.'
$Header2 = '# "@<path>" opens a document; rows: ID|first-last|status|title'
$StatusHeading = 'Status'
$StatusMarker = '**Status**'
$Blanks = [char[]]@(' ', "`t")
$HeadingRx = [regex]'^(#{1,6})(?:[ \t]|$)'
$IdRx = [regex]'^(FTR|RQ|ADR|DEC|PLAN|TASK)-[A-Z]{3}-[0-9]{3}'
$IdBoundaryRx = [regex]'^[ \t:]'
$FenceOpenRx = [regex]'^[ \t]*(```+|~~~+)'
$FenceCloseRx = [regex]'^[ \t]*(`+|~+)[ \t]*$'
$StatusFieldRx = [regex]'^[ \t]*(?:[-*+][ \t]+)?\*\*Status\*\*[ \t]*:'
$BlankLineRx = [regex]'^[ \t]*$'
$IdNumberLength = 3
# RQ-IDX-017: helpers are inlined below - a PowerShell function call costs ~0.1 ms.

$cwd = (Get-Location).ProviderPath
if (-not (Test-Path -LiteralPath (Join-Path $cwd $ProcessDir) -PathType Container)) {
    [Console]::Error.WriteLine("agnos-index: '$ProcessDir' folder not found - run from the repository root")
    exit 1
}

# RQ-IDX-001: documents to index, in ordinal path order (RQ-IDX-005).
$pathList = New-Object System.Collections.Generic.List[string]
foreach ($dir in $ScanDirs) {
    $root = Join-Path (Join-Path $cwd $ProcessDir) $dir
    if (Test-Path -LiteralPath $root -PathType Container) {
        foreach ($name in (Get-ChildItem -LiteralPath $root -Recurse -File -Force -Name)) {
            if ($name -match $IncludeRx -and $name -notmatch $ExcludeRx) {
                $pathList.Add("$ProcessDir/$dir/" + $name.Replace('\', '/'))
            }
        }
    }
}
$paths = $pathList.ToArray()
[Array]::Sort($paths, [StringComparer]::Ordinal)

$entries = New-Object System.Collections.Generic.List[object]
$groups = New-Object System.Collections.Generic.List[object]
$seen = New-Object System.Collections.Hashtable ([StringComparer]::Ordinal)
$maxByPrefix = New-Object System.Collections.Specialized.OrderedDictionary
$duplicates = New-Object System.Collections.Generic.List[string]

# RQ-IDX-002 to RQ-IDX-004, RQ-IDX-006, RQ-IDX-007: one pass per document.
foreach ($rel in $paths) {
    $lines = [IO.File]::ReadAllLines((Join-Path $cwd $rel))
    $firstEntry = $entries.Count
    $stack = New-Object System.Collections.Generic.List[object]
    $inFence = $false
    $fenceChar = ''
    $fenceLength = 0
    $awaiting = $null
    $ln = 0
    foreach ($line in $lines) {
        $ln++
        if ($inFence) {
            if ($FenceCloseRx.IsMatch($line)) {
                $marker = $line.Trim($Blanks)
                if ($marker.Substring(0, 1) -ceq $fenceChar -and $marker.Length -ge $fenceLength) { $inFence = $false }
            }
            continue
        }
        # RQ-IDX-017: cheap character pre-filters before any regex.
        $hasFenceChar = $line.IndexOf([char]'`') -ge 0 -or $line.IndexOf([char]'~') -ge 0
        $fence = if ($hasFenceChar) { $FenceOpenRx.Match($line) } else { $null }
        if ($null -ne $fence -and $fence.Success) {
            $inFence = $true
            $fenceChar = $fence.Groups[1].Value.Substring(0, 1)
            $fenceLength = $fence.Groups[1].Value.Length
            $awaiting = $null
            continue
        }
        $heading = if ($line.StartsWith('#', [StringComparison]::Ordinal)) { $HeadingRx.Match($line) } else { $null }
        if ($null -ne $heading -and $heading.Success) {
            $level = $heading.Groups[1].Length
            $text = $line.Substring($level).Trim($Blanks)
            $awaiting = $null
            # DEC-IDX-002: a heading of level L closes every open section of level >= L.
            while ($stack.Count -gt 0 -and $stack[$stack.Count - 1].Level -ge $level) {
                $stack[$stack.Count - 1].Entry.Last = $ln - 1
                $stack.RemoveAt($stack.Count - 1)
            }
            $idMatch = $IdRx.Match($text)
            if ($idMatch.Success) {
                $rest = $text.Substring($idMatch.Length)
                if ($rest.Length -eq 0 -or $IdBoundaryRx.IsMatch($rest)) {
                    $title = $rest.Trim($Blanks)
                    if ($title.StartsWith(':', [StringComparison]::Ordinal)) { $title = $title.Substring(1).Trim($Blanks) }
                    $id = $idMatch.Value
                    $entry = [pscustomobject]@{ Id = $id; First = $ln; Last = 0; Status = ''; HasStatus = $false; Title = $title }
                    $entries.Add($entry)
                    $stack.Add(@{ Entry = $entry; Level = $level })
                    if ($seen.ContainsKey($id)) {
                        $duplicates.Add("agnos-index: DUPLICATE $id ${rel}:$ln (first: $($seen[$id]))")
                    } else {
                        $seen[$id] = "${rel}:$ln"
                    }
                    $prefix = $id.Substring(0, $id.Length - $IdNumberLength - 1)
                    $number = [int]$id.Substring($id.Length - $IdNumberLength)
                    if (-not $maxByPrefix.Contains($prefix) -or $number -gt $maxByPrefix[$prefix]) { $maxByPrefix[$prefix] = $number }
                }
            } elseif ($text -ceq $StatusHeading -and $stack.Count -gt 0) {
                $awaiting = $stack[$stack.Count - 1].Entry
            }
            continue
        }
        if ($stack.Count -gt 0 -and $line.IndexOf($StatusMarker, [StringComparison]::Ordinal) -ge 0) {
            $statusField = $StatusFieldRx.Match($line)
            if ($statusField.Success) {
                $awaiting = $null
                # RQ-IDX-004: first status field wins; '|' would break the row format.
                $target = $stack[$stack.Count - 1].Entry
                if (-not $target.HasStatus) {
                    $target.HasStatus = $true
                    $target.Status = $line.Substring($statusField.Length).Trim($Blanks).Replace('|', '/')
                }
                continue
            }
        }
        if ($null -ne $awaiting -and -not $BlankLineRx.IsMatch($line)) {
            if (-not $awaiting.HasStatus) {
                $awaiting.HasStatus = $true
                $awaiting.Status = $line.Trim($Blanks).Replace('|', '/')
            }
            $awaiting = $null
        }
    }
    foreach ($open in $stack) { $open.Entry.Last = $ln }
    $groups.Add(@{ Path = $rel; First = $firstEntry; End = $entries.Count })
}

# RQ-IDX-005, RQ-IDX-006: index layout.
$sb = New-Object System.Text.StringBuilder
[void]$sb.Append($Header1).Append("`n").Append($Header2).Append("`n").Append('#next')
foreach ($prefix in $maxByPrefix.Keys) {
    [void]$sb.Append(' ').Append($prefix).Append('-').Append(($maxByPrefix[$prefix] + 1).ToString('000'))
}
[void]$sb.Append("`n")
foreach ($group in $groups) {
    [void]$sb.Append('@').Append($group.Path).Append("`n")
    for ($i = $group.First; $i -lt $group.End; $i++) {
        $e = $entries[$i]
        [void]$sb.Append($e.Id).Append('|').Append($e.First).Append('-').Append($e.Last).Append('|').Append($e.Status).Append('|').Append($e.Title).Append("`n")
    }
}
$content = $sb.ToString()

# RQ-IDX-009: rewrite only on change, UTF-8 without BOM (RQ-IDX-015).
$encoding = New-Object System.Text.UTF8Encoding $false
$indexPath = Join-Path $cwd $IndexFile
$state = 'updated'
if ([IO.File]::Exists($indexPath) -and [string]::Equals($encoding.GetString([IO.File]::ReadAllBytes($indexPath)), $content, [StringComparison]::Ordinal)) {
    $state = 'unchanged'
} else {
    [IO.File]::WriteAllText($indexPath, $content, $encoding)
}

foreach ($d in $duplicates) { [Console]::Error.WriteLine($d) }
[Console]::Out.WriteLine("agnos-index: $($entries.Count) entries, $($paths.Count) documents, $IndexFile $state")
if ($duplicates.Count -gt 0) { exit 2 }
exit 0
