/*
XS56K - a realtime editor for the AKAI S5000/S6000 samplers
Copyright (C) 2026 https://github.com/xplorer2716

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/
// GENERATED by juce/tools/generate_akm_items.py from juce/akm/data/items.json - do not edit. Change the
// data file, regenerate, and review both diffs; `--check` fails when this file is out of date.
// [RQ-AKM-011, RQ-AKM-012, RQ-AKM-013, RQ-AKM-014, RQ-AKM-015, RQ-AKM-044, ADR-AKM-001 (DEC-AKM-003, DEC-AKM-012)]
#pragma once

#include <array>
#include <cstddef>

#include "akm/ItemDescriptor.hpp"

namespace akm
{
    /// One enumerator per record of the data file, in its order; the value is the record's index in
    /// ITEM_TABLE.
    enum class ItemId : std::size_t
    {
        SysExQuery,
        SysExNotification,
        SysExSyncLcd,
        SysExChecksum,
        SysExAutoScreenUpdate,
        SysExEcho,
        SysExStillAlive,
        SystemOsVersion,
        SystemOsSubVersion,
    };

    namespace item_data
    {
        inline constexpr std::array<ValueSpec, 1> SYS_EX_NOTIFICATION_ARGS{{
            {"enabled", ValueFormat::Byte, 0, 1},
        }};
        inline constexpr std::array<ValueSpec, 1> SYS_EX_SYNC_LCD_ARGS{{
            {"enabled", ValueFormat::Byte, 0, 1},
        }};
        inline constexpr std::array<ValueSpec, 1> SYS_EX_CHECKSUM_ARGS{{
            {"enabled", ValueFormat::Byte, 0, 1},
        }};
        inline constexpr std::array<ValueSpec, 1> SYS_EX_AUTO_SCREEN_UPDATE_ARGS{{
            {"enabled", ValueFormat::Byte, 0, 1},
        }};
        inline constexpr std::array<ValueSpec, 4> SYS_EX_ECHO_ARGS{{
            {"data1", ValueFormat::Byte, 0, 127},
            {"data2", ValueFormat::Byte, 0, 127},
            {"data3", ValueFormat::Byte, 0, 127},
            {"data4", ValueFormat::Byte, 0, 127},
        }};
        inline constexpr std::array<ValueSpec, 4> SYS_EX_ECHO_REPLY{{
            {"data1", ValueFormat::Byte, 0, 127},
            {"data2", ValueFormat::Byte, 0, 127},
            {"data3", ValueFormat::Byte, 0, 127},
            {"data4", ValueFormat::Byte, 0, 127},
        }};
        inline constexpr std::array<ValueSpec, 1> SYS_EX_STILL_ALIVE_ARGS{{
            {"enabled", ValueFormat::Byte, 0, 1},
        }};
        inline constexpr std::array<ValueSpec, 2> SYSTEM_OS_VERSION_REPLY{{
            {"major", ValueFormat::Byte, 0, 127},
            {"minor", ValueFormat::Byte, 0, 127},
        }};
        inline constexpr std::array<ValueSpec, 1> SYSTEM_OS_SUB_VERSION_REPLY{{
            {"subVersion", ValueFormat::Byte, 0, 127},
        }};
    }

    /// Every record of the data file, indexed by ItemId.
    inline constexpr std::array<ItemDescriptor, 9> ITEM_TABLE{{
        // section 00 item 00 [RQ-AKM-012]
        {"Query", 0x00, 0x00, ItemKind::Set, {}, {}},
        // section 00 item 01 [RQ-AKM-014]
        {"Notification", 0x00, 0x01, ItemKind::Set, item_data::SYS_EX_NOTIFICATION_ARGS, {}},
        // section 00 item 03 [RQ-AKM-014]
        {"Sync LCD", 0x00, 0x03, ItemKind::Set, item_data::SYS_EX_SYNC_LCD_ARGS, {}},
        // section 00 item 04 [RQ-AKM-013]
        {"Checksum verification", 0x00, 0x04, ItemKind::Set, item_data::SYS_EX_CHECKSUM_ARGS, {}},
        // section 00 item 05 [RQ-AKM-014]
        {"Auto screen update", 0x00, 0x05, ItemKind::Set, item_data::SYS_EX_AUTO_SCREEN_UPDATE_ARGS, {}},
        // section 00 item 06 [RQ-AKM-015]
        {"Echo", 0x00, 0x06, ItemKind::Get, item_data::SYS_EX_ECHO_ARGS, item_data::SYS_EX_ECHO_REPLY},
        // section 00 item 07 [RQ-AKM-011, RQ-AKM-014]
        {"Still Alive monitor", 0x00, 0x07, ItemKind::Set, item_data::SYS_EX_STILL_ALIVE_ARGS, {}},
        // section 02 item 00 [RQ-AKM-044]
        {"Operating system version", 0x02, 0x00, ItemKind::Get, {}, item_data::SYSTEM_OS_VERSION_REPLY},
        // section 02 item 01 [RQ-AKM-044]
        {"Operating system sub-version", 0x02, 0x01, ItemKind::Get, {}, item_data::SYSTEM_OS_SUB_VERSION_REPLY},
    }};
}
