/*
XS56K - a realtime editor for the AKAI S5000/S6000 samplers
Copyright (C) 2026 https://github.com/xplorer2716

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/
// GENERATED by juce/tools/generate_akm_items.py from juce/akm/data/items.json - do not edit. Change the
// data file, regenerate, and review both diffs; `--check` fails when this file is out of date.
// [RQ-AKM-011, RQ-AKM-012, RQ-AKM-013, RQ-AKM-014, RQ-AKM-015, RQ-AKM-021, RQ-AKM-022, RQ-AKM-023, RQ-AKM-024, RQ-AKM-025, RQ-AKM-028, RQ-AKM-029, RQ-AKM-030, RQ-AKM-032, RQ-AKM-034, RQ-AKM-035, RQ-AKM-037, RQ-AKM-044, RQ-AKM-045, RQ-AKM-046, RQ-AKM-047, ADR-AKM-001 (DEC-AKM-003, DEC-AKM-012)]
#pragma once

#include <array>
#include <cstddef>

#include "akm/ItemDescriptor.hpp"

namespace akm
{
    /// One enumerator per record of the data file, in its order; the value is the record's index in
    /// ITEM_TABLE.
    enum class ItemId : std::size_t
    {
        SysExQuery,
        SysExNotification,
        SysExSyncLcd,
        SysExChecksum,
        SysExAutoScreenUpdate,
        SysExEcho,
        SysExStillAlive,
        SystemOsVersion,
        SystemOsSubVersion,
        ProgramCreate,
        ProgramCreateWithKeygroups,
        ProgramSelectByName,
        ProgramSelectByIndex,
        ProgramDeleteCurrent,
        ProgramRenameCurrent,
        ProgramGetCount,
        ProgramGetCurrentName,
        ProgramSetLoudness,
        ProgramSetVelocitySensitivity,
        ProgramSetAmpModSource,
        ProgramSetAmpModValue,
        ProgramSetPanModSource,
        ProgramSetPanModValue,
        ProgramGetLoudness,
        ProgramGetVelocitySensitivity,
        ProgramGetAmpModSource,
        ProgramGetAmpModValue,
        ProgramGetPanModSource,
        ProgramGetPanModValue,
        ProgramSetSemitoneTune,
        ProgramSetFineTune,
        ProgramSetTuneTemplate,
        ProgramSetUserTuneTemplate,
        ProgramSetKey,
        ProgramGetSemitoneTune,
        ProgramGetFineTune,
        ProgramGetTuneTemplate,
        ProgramGetUserTuneTemplate,
        ProgramGetKey,
        ProgramSetPitchBendUp,
        ProgramSetPitchBendDown,
        ProgramSetBendMode,
        ProgramSetAftertouchValue,
        ProgramSetLegato,
        ProgramSetPortamentoEnable,
        ProgramSetPortamentoMode,
        ProgramSetPortamentoTime,
        ProgramGetPitchBendUp,
        ProgramGetPitchBendDown,
        ProgramGetBendMode,
        ProgramGetAftertouchValue,
        ProgramGetLegato,
        ProgramGetPortamentoEnable,
        ProgramGetPortamentoMode,
        ProgramGetPortamentoTime,
        ProgramSetLfoRate,
        ProgramSetLfoDelay,
        ProgramSetLfoDepth,
        ProgramSetLfoWaveform,
        ProgramSetLfoSync,
        ProgramSetLfoRetrigger,
        ProgramSetLfoRateModSource,
        ProgramSetLfoRateModValue,
        ProgramSetLfoDelayModSource,
        ProgramSetLfoDelayModValue,
        ProgramSetLfoDepthModSource,
        ProgramSetLfoDepthModValue,
        ProgramSetLfoModwheel,
        ProgramSetLfoAftertouch,
        ProgramSetLfoMidiClockSyncEnable,
        ProgramSetLfoMidiClockSyncDivision,
        ProgramGetLfoRate,
        ProgramGetLfoDelay,
        ProgramGetLfoDepth,
        ProgramGetLfoWaveform,
        ProgramGetLfoSync,
        ProgramGetLfoRetrigger,
        ProgramGetLfoRateModSource,
        ProgramGetLfoRateModValue,
        ProgramGetLfoDelayModSource,
        ProgramGetLfoDelayModValue,
        ProgramGetLfoDepthModSource,
        ProgramGetLfoDepthModValue,
        ProgramGetLfoModwheel,
        ProgramGetLfoAftertouch,
        ProgramGetLfoMidiClockSyncEnable,
        ProgramGetLfoMidiClockSyncDivision,
        ProgramSetPitchModSource,
        ProgramSetKeygroupAmpModSource,
        ProgramSetFilterModInputSource,
        ProgramGetPitchModSource,
        ProgramGetKeygroupAmpModSource,
        ProgramGetFilterModInputSource,
        ProgramSetNumber,
        ProgramAddKeygroups,
        ProgramDeleteKeygroup,
        ProgramSetCrossfade,
        ProgramGetNumber,
        ProgramGetKeygroupCount,
        ProgramGetCrossfade,
        ProgramGetIndex,
        ProgramGetAllNumbers,
        ProgramGetAllNames,
        ProgramDeleteAll,
        KeygroupSelect,
        KeygroupGetCurrent,
        KeygroupSetLowNote,
        KeygroupSetHighNote,
        KeygroupSetMuteGroup,
        KeygroupSetFxOverride,
        KeygroupSetFxSendLevel,
        KeygroupSetZoneCrossfade,
        KeygroupGetLowNote,
        KeygroupGetHighNote,
        KeygroupGetMuteGroup,
        KeygroupGetFxOverride,
        KeygroupGetFxSendLevel,
        KeygroupGetZoneCrossfade,
        KeygroupSetSemitoneTune,
        KeygroupSetFineTune,
        KeygroupSetLevel,
        KeygroupSetPitchModValue,
        KeygroupSetAmpModValue,
        KeygroupGetSemitoneTune,
        KeygroupGetFineTune,
        KeygroupGetLevel,
        KeygroupGetPitchModValue,
        KeygroupGetAmpModValue,
        KeygroupSetFilterMode,
        KeygroupSetFilterCutoff,
        KeygroupSetFilterResonance,
        KeygroupSetFilterKeyboardTrack,
        KeygroupSetFilterModInputValue,
        KeygroupSetFilterAttenuation,
        KeygroupGetFilterMode,
        KeygroupGetFilterCutoff,
        KeygroupGetFilterResonance,
        KeygroupGetFilterKeyboardTrack,
        KeygroupGetFilterModInputValue,
        KeygroupGetFilterAttenuation,
        KeygroupSetFilterEnvAttack,
        KeygroupSetFilterEnvVelocityToAttack,
        KeygroupSetFilterEnvDecay,
        KeygroupSetFilterEnvSustain,
        KeygroupSetFilterEnvRelease,
        KeygroupSetFilterEnvOnVelocityToRelease,
        KeygroupSetFilterEnvKeyscale,
        KeygroupSetFilterEnvDepth,
        KeygroupSetFilterEnvOffVelocityToRelease,
        KeygroupGetFilterEnvAttack,
        KeygroupGetFilterEnvVelocityToAttack,
        KeygroupGetFilterEnvDecay,
        KeygroupGetFilterEnvSustain,
        KeygroupGetFilterEnvRelease,
        KeygroupGetFilterEnvOnVelocityToRelease,
        KeygroupGetFilterEnvKeyscale,
        KeygroupGetFilterEnvDepth,
        KeygroupGetFilterEnvOffVelocityToRelease,
        KeygroupSetAmpEnvAttack,
        KeygroupSetAmpEnvVelocityToAttack,
        KeygroupSetAmpEnvDecay,
        KeygroupSetAmpEnvSustain,
        KeygroupSetAmpEnvRelease,
        KeygroupSetAmpEnvOnVelocityToRelease,
        KeygroupSetAmpEnvKeyscale,
        KeygroupSetAmpEnvOffVelocityToRelease,
        KeygroupGetAmpEnvAttack,
        KeygroupGetAmpEnvVelocityToAttack,
        KeygroupGetAmpEnvDecay,
        KeygroupGetAmpEnvSustain,
        KeygroupGetAmpEnvRelease,
        KeygroupGetAmpEnvOnVelocityToRelease,
        KeygroupGetAmpEnvKeyscale,
        KeygroupGetAmpEnvOffVelocityToRelease,
        KeygroupSetAuxEnvRate,
        KeygroupSetAuxEnvVelocityToRate,
        KeygroupSetAuxEnvKeyboardToR2R4,
        KeygroupSetAuxEnvLevel,
        KeygroupSetAuxEnvOffVelocityToRate,
        KeygroupGetAuxEnvRate,
        KeygroupGetAuxEnvVelocityToRate,
        KeygroupGetAuxEnvKeyboardToR2R4,
        KeygroupGetAuxEnvLevel,
        KeygroupGetAuxEnvOffVelocityToRate,
        ZoneSetSample,
        ZoneSetLevel,
        ZoneSetPanBalance,
        ZoneSetOutput,
        ZoneSetFilter,
        ZoneSetFineTune,
        ZoneSetSemitoneTune,
        ZoneSetKeyboardTrack,
        ZoneSetPlayback,
        ZoneSetVelocityToStart,
        ZoneSetHighVelocity,
        ZoneSetLowVelocity,
        ZoneSetMute,
        ZoneSetSolo,
        ZoneGetSample,
        ZoneGetLevel,
        ZoneGetPanBalance,
        ZoneGetOutput,
        ZoneGetFilter,
        ZoneGetFineTune,
        ZoneGetSemitoneTune,
        ZoneGetKeyboardTrack,
        ZoneGetPlayback,
        ZoneGetVelocityToStart,
        ZoneGetHighVelocity,
        ZoneGetLowVelocity,
        ZoneGetMute,
        ZoneGetSolo,
        SampleSelectByName,
        SampleSelectByIndex,
        SampleDeleteCurrent,
        SampleRenameCurrent,
        SampleStartAudition,
        SampleStopAudition,
        SampleGetCurrentIndex,
        SampleGetCurrentName,
        SampleDeleteAll,
    };

    namespace item_data
    {
        inline constexpr std::array<ValueSpec, 1> SYS_EX_NOTIFICATION_ARGS{{
            {"enabled", ValueFormat::Byte, 0, 1},
        }};
        inline constexpr std::array<ValueSpec, 1> SYS_EX_SYNC_LCD_ARGS{{
            {"enabled", ValueFormat::Byte, 0, 1},
        }};
        inline constexpr std::array<ValueSpec, 1> SYS_EX_CHECKSUM_ARGS{{
            {"enabled", ValueFormat::Byte, 0, 1},
        }};
        inline constexpr std::array<ValueSpec, 1> SYS_EX_AUTO_SCREEN_UPDATE_ARGS{{
            {"enabled", ValueFormat::Byte, 0, 1},
        }};
        inline constexpr std::array<ValueSpec, 4> SYS_EX_ECHO_ARGS{{
            {"data1", ValueFormat::Byte, 0, 127},
            {"data2", ValueFormat::Byte, 0, 127},
            {"data3", ValueFormat::Byte, 0, 127},
            {"data4", ValueFormat::Byte, 0, 127},
        }};
        inline constexpr std::array<ValueSpec, 4> SYS_EX_ECHO_REPLY{{
            {"data1", ValueFormat::Byte, 0, 127},
            {"data2", ValueFormat::Byte, 0, 127},
            {"data3", ValueFormat::Byte, 0, 127},
            {"data4", ValueFormat::Byte, 0, 127},
        }};
        inline constexpr std::array<ValueSpec, 1> SYS_EX_STILL_ALIVE_ARGS{{
            {"enabled", ValueFormat::Byte, 0, 1},
        }};
        inline constexpr std::array<ValueSpec, 2> SYSTEM_OS_VERSION_REPLY{{
            {"major", ValueFormat::Byte, 0, 127},
            {"minor", ValueFormat::Byte, 0, 127},
        }};
        inline constexpr std::array<ValueSpec, 1> SYSTEM_OS_SUB_VERSION_REPLY{{
            {"subVersion", ValueFormat::Byte, 0, 127},
        }};
        inline constexpr std::array<ValueSpec, 1> PROGRAM_CREATE_ARGS{{
            {"name", ValueFormat::String, 0, 20},
        }};
        inline constexpr std::array<ValueSpec, 2> PROGRAM_CREATE_WITH_KEYGROUPS_ARGS{{
            {"keygroupCount", ValueFormat::Byte, 1, 99},
            {"name", ValueFormat::String, 0, 20},
        }};
        inline constexpr std::array<ValueSpec, 1> PROGRAM_SELECT_BY_NAME_ARGS{{
            {"name", ValueFormat::String, 0, 20},
        }};
        inline constexpr std::array<ValueSpec, 2> PROGRAM_SELECT_BY_INDEX_ARGS{{
            {"indexMsb", ValueFormat::Byte, 0, 127},
            {"indexLsb", ValueFormat::Byte, 0, 127},
        }};
        inline constexpr std::array<ValueSpec, 1> PROGRAM_RENAME_CURRENT_ARGS{{
            {"name", ValueFormat::String, 0, 20},
        }};
        inline constexpr std::array<ValueSpec, 2> PROGRAM_GET_COUNT_REPLY{{
            {"countMsb", ValueFormat::Byte, 0, 127},
            {"countLsb", ValueFormat::Byte, 0, 127},
        }};
        inline constexpr std::array<ValueSpec, 1> PROGRAM_GET_CURRENT_NAME_REPLY{{
            {"name", ValueFormat::String, 0, 20},
        }};
        inline constexpr std::array<ValueSpec, 1> PROGRAM_SET_LOUDNESS_ARGS{{
            {"loudness", ValueFormat::Byte, 0, 100},
        }};
        inline constexpr std::array<ValueSpec, 2> PROGRAM_SET_VELOCITY_SENSITIVITY_ARGS{{
            {"sign", ValueFormat::Byte, 0, 1},
            {"magnitude", ValueFormat::Byte, 0, 100},
        }};
        inline constexpr std::array<ValueSpec, 2> PROGRAM_SET_AMP_MOD_SOURCE_ARGS{{
            {"ampMod", ValueFormat::Byte, 1, 2},
            {"source", ValueFormat::Byte, 0, 14},
        }};
        inline constexpr std::array<ValueSpec, 3> PROGRAM_SET_AMP_MOD_VALUE_ARGS{{
            {"ampMod", ValueFormat::Byte, 1, 2},
            {"sign", ValueFormat::Byte, 0, 1},
            {"magnitude", ValueFormat::Byte, 0, 100},
        }};
        inline constexpr std::array<ValueSpec, 2> PROGRAM_SET_PAN_MOD_SOURCE_ARGS{{
            {"panMod", ValueFormat::Byte, 1, 3},
            {"source", ValueFormat::Byte, 0, 14},
        }};
        inline constexpr std::array<ValueSpec, 3> PROGRAM_SET_PAN_MOD_VALUE_ARGS{{
            {"panMod", ValueFormat::Byte, 1, 3},
            {"sign", ValueFormat::Byte, 0, 1},
            {"magnitude", ValueFormat::Byte, 0, 100},
        }};
        inline constexpr std::array<ValueSpec, 1> PROGRAM_GET_LOUDNESS_REPLY{{
            {"loudness", ValueFormat::Byte, 0, 100},
        }};
        inline constexpr std::array<ValueSpec, 2> PROGRAM_GET_VELOCITY_SENSITIVITY_REPLY{{
            {"sign", ValueFormat::Byte, 0, 1},
            {"magnitude", ValueFormat::Byte, 0, 100},
        }};
        inline constexpr std::array<ValueSpec, 1> PROGRAM_GET_AMP_MOD_SOURCE_ARGS{{
            {"ampMod", ValueFormat::Byte, 1, 2},
        }};
        inline constexpr std::array<ValueSpec, 1> PROGRAM_GET_AMP_MOD_SOURCE_REPLY{{
            {"source", ValueFormat::Byte, 0, 14},
        }};
        inline constexpr std::array<ValueSpec, 1> PROGRAM_GET_AMP_MOD_VALUE_ARGS{{
            {"ampMod", ValueFormat::Byte, 1, 2},
        }};
        inline constexpr std::array<ValueSpec, 2> PROGRAM_GET_AMP_MOD_VALUE_REPLY{{
            {"sign", ValueFormat::Byte, 0, 1},
            {"magnitude", ValueFormat::Byte, 0, 100},
        }};
        inline constexpr std::array<ValueSpec, 1> PROGRAM_GET_PAN_MOD_SOURCE_ARGS{{
            {"panMod", ValueFormat::Byte, 1, 3},
        }};
        inline constexpr std::array<ValueSpec, 1> PROGRAM_GET_PAN_MOD_SOURCE_REPLY{{
            {"source", ValueFormat::Byte, 0, 14},
        }};
        inline constexpr std::array<ValueSpec, 1> PROGRAM_GET_PAN_MOD_VALUE_ARGS{{
            {"panMod", ValueFormat::Byte, 1, 3},
        }};
        inline constexpr std::array<ValueSpec, 2> PROGRAM_GET_PAN_MOD_VALUE_REPLY{{
            {"sign", ValueFormat::Byte, 0, 1},
            {"magnitude", ValueFormat::Byte, 0, 100},
        }};
        inline constexpr std::array<ValueSpec, 2> PROGRAM_SET_SEMITONE_TUNE_ARGS{{
            {"sign", ValueFormat::Byte, 0, 1},
            {"magnitude", ValueFormat::Byte, 0, 36},
        }};
        inline constexpr std::array<ValueSpec, 2> PROGRAM_SET_FINE_TUNE_ARGS{{
            {"sign", ValueFormat::Byte, 0, 1},
            {"magnitude", ValueFormat::Byte, 0, 50},
        }};
        inline constexpr std::array<ValueSpec, 1> PROGRAM_SET_TUNE_TEMPLATE_ARGS{{
            {"template", ValueFormat::Byte, 0, 7},
        }};
        inline constexpr std::array<ValueSpec, 24> PROGRAM_SET_USER_TUNE_TEMPLATE_ARGS{{
            {"note0Sign", ValueFormat::Byte, 0, 1},
            {"note0Magnitude", ValueFormat::Byte, 0, 50},
            {"note1Sign", ValueFormat::Byte, 0, 1},
            {"note1Magnitude", ValueFormat::Byte, 0, 50},
            {"note2Sign", ValueFormat::Byte, 0, 1},
            {"note2Magnitude", ValueFormat::Byte, 0, 50},
            {"note3Sign", ValueFormat::Byte, 0, 1},
            {"note3Magnitude", ValueFormat::Byte, 0, 50},
            {"note4Sign", ValueFormat::Byte, 0, 1},
            {"note4Magnitude", ValueFormat::Byte, 0, 50},
            {"note5Sign", ValueFormat::Byte, 0, 1},
            {"note5Magnitude", ValueFormat::Byte, 0, 50},
            {"note6Sign", ValueFormat::Byte, 0, 1},
            {"note6Magnitude", ValueFormat::Byte, 0, 50},
            {"note7Sign", ValueFormat::Byte, 0, 1},
            {"note7Magnitude", ValueFormat::Byte, 0, 50},
            {"note8Sign", ValueFormat::Byte, 0, 1},
            {"note8Magnitude", ValueFormat::Byte, 0, 50},
            {"note9Sign", ValueFormat::Byte, 0, 1},
            {"note9Magnitude", ValueFormat::Byte, 0, 50},
            {"note10Sign", ValueFormat::Byte, 0, 1},
            {"note10Magnitude", ValueFormat::Byte, 0, 50},
            {"note11Sign", ValueFormat::Byte, 0, 1},
            {"note11Magnitude", ValueFormat::Byte, 0, 50},
        }};
        inline constexpr std::array<ValueSpec, 1> PROGRAM_SET_KEY_ARGS{{
            {"key", ValueFormat::Byte, 0, 11},
        }};
        inline constexpr std::array<ValueSpec, 2> PROGRAM_GET_SEMITONE_TUNE_REPLY{{
            {"sign", ValueFormat::Byte, 0, 1},
            {"magnitude", ValueFormat::Byte, 0, 36},
        }};
        inline constexpr std::array<ValueSpec, 2> PROGRAM_GET_FINE_TUNE_REPLY{{
            {"sign", ValueFormat::Byte, 0, 1},
            {"magnitude", ValueFormat::Byte, 0, 50},
        }};
        inline constexpr std::array<ValueSpec, 1> PROGRAM_GET_TUNE_TEMPLATE_REPLY{{
            {"template", ValueFormat::Byte, 0, 7},
        }};
        inline constexpr std::array<ValueSpec, 24> PROGRAM_GET_USER_TUNE_TEMPLATE_REPLY{{
            {"note0Sign", ValueFormat::Byte, 0, 1},
            {"note0Magnitude", ValueFormat::Byte, 0, 50},
            {"note1Sign", ValueFormat::Byte, 0, 1},
            {"note1Magnitude", ValueFormat::Byte, 0, 50},
            {"note2Sign", ValueFormat::Byte, 0, 1},
            {"note2Magnitude", ValueFormat::Byte, 0, 50},
            {"note3Sign", ValueFormat::Byte, 0, 1},
            {"note3Magnitude", ValueFormat::Byte, 0, 50},
            {"note4Sign", ValueFormat::Byte, 0, 1},
            {"note4Magnitude", ValueFormat::Byte, 0, 50},
            {"note5Sign", ValueFormat::Byte, 0, 1},
            {"note5Magnitude", ValueFormat::Byte, 0, 50},
            {"note6Sign", ValueFormat::Byte, 0, 1},
            {"note6Magnitude", ValueFormat::Byte, 0, 50},
            {"note7Sign", ValueFormat::Byte, 0, 1},
            {"note7Magnitude", ValueFormat::Byte, 0, 50},
            {"note8Sign", ValueFormat::Byte, 0, 1},
            {"note8Magnitude", ValueFormat::Byte, 0, 50},
            {"note9Sign", ValueFormat::Byte, 0, 1},
            {"note9Magnitude", ValueFormat::Byte, 0, 50},
            {"note10Sign", ValueFormat::Byte, 0, 1},
            {"note10Magnitude", ValueFormat::Byte, 0, 50},
            {"note11Sign", ValueFormat::Byte, 0, 1},
            {"note11Magnitude", ValueFormat::Byte, 0, 50},
        }};
        inline constexpr std::array<ValueSpec, 1> PROGRAM_GET_KEY_REPLY{{
            {"key", ValueFormat::Byte, 0, 11},
        }};
        inline constexpr std::array<ValueSpec, 1> PROGRAM_SET_PITCH_BEND_UP_ARGS{{
            {"semitones", ValueFormat::Byte, 0, 24},
        }};
        inline constexpr std::array<ValueSpec, 1> PROGRAM_SET_PITCH_BEND_DOWN_ARGS{{
            {"semitones", ValueFormat::Byte, 0, 24},
        }};
        inline constexpr std::array<ValueSpec, 1> PROGRAM_SET_BEND_MODE_ARGS{{
            {"mode", ValueFormat::Byte, 0, 1},
        }};
        inline constexpr std::array<ValueSpec, 2> PROGRAM_SET_AFTERTOUCH_VALUE_ARGS{{
            {"sign", ValueFormat::Byte, 0, 1},
            {"magnitude", ValueFormat::Byte, 0, 12},
        }};
        inline constexpr std::array<ValueSpec, 1> PROGRAM_SET_LEGATO_ARGS{{
            {"mode", ValueFormat::Byte, 0, 1},
        }};
        inline constexpr std::array<ValueSpec, 1> PROGRAM_SET_PORTAMENTO_ENABLE_ARGS{{
            {"mode", ValueFormat::Byte, 0, 1},
        }};
        inline constexpr std::array<ValueSpec, 1> PROGRAM_SET_PORTAMENTO_MODE_ARGS{{
            {"mode", ValueFormat::Byte, 0, 1},
        }};
        inline constexpr std::array<ValueSpec, 1> PROGRAM_SET_PORTAMENTO_TIME_ARGS{{
            {"time", ValueFormat::Byte, 0, 100},
        }};
        inline constexpr std::array<ValueSpec, 1> PROGRAM_GET_PITCH_BEND_UP_REPLY{{
            {"semitones", ValueFormat::Byte, 0, 24},
        }};
        inline constexpr std::array<ValueSpec, 1> PROGRAM_GET_PITCH_BEND_DOWN_REPLY{{
            {"semitones", ValueFormat::Byte, 0, 24},
        }};
        inline constexpr std::array<ValueSpec, 1> PROGRAM_GET_BEND_MODE_REPLY{{
            {"mode", ValueFormat::Byte, 0, 1},
        }};
        inline constexpr std::array<ValueSpec, 2> PROGRAM_GET_AFTERTOUCH_VALUE_REPLY{{
            {"sign", ValueFormat::Byte, 0, 1},
            {"magnitude", ValueFormat::Byte, 0, 12},
        }};
        inline constexpr std::array<ValueSpec, 1> PROGRAM_GET_LEGATO_REPLY{{
            {"mode", ValueFormat::Byte, 0, 1},
        }};
        inline constexpr std::array<ValueSpec, 1> PROGRAM_GET_PORTAMENTO_ENABLE_REPLY{{
            {"mode", ValueFormat::Byte, 0, 1},
        }};
        inline constexpr std::array<ValueSpec, 1> PROGRAM_GET_PORTAMENTO_MODE_REPLY{{
            {"mode", ValueFormat::Byte, 0, 1},
        }};
        inline constexpr std::array<ValueSpec, 1> PROGRAM_GET_PORTAMENTO_TIME_REPLY{{
            {"time", ValueFormat::Byte, 0, 100},
        }};
        inline constexpr std::array<ValueSpec, 2> PROGRAM_SET_LFO_RATE_ARGS{{
            {"lfo", ValueFormat::Byte, 1, 2},
            {"rate", ValueFormat::Byte, 0, 100},
        }};
        inline constexpr std::array<ValueSpec, 2> PROGRAM_SET_LFO_DELAY_ARGS{{
            {"lfo", ValueFormat::Byte, 1, 2},
            {"delay", ValueFormat::Byte, 0, 100},
        }};
        inline constexpr std::array<ValueSpec, 2> PROGRAM_SET_LFO_DEPTH_ARGS{{
            {"lfo", ValueFormat::Byte, 1, 2},
            {"depth", ValueFormat::Byte, 0, 100},
        }};
        inline constexpr std::array<ValueSpec, 2> PROGRAM_SET_LFO_WAVEFORM_ARGS{{
            {"lfo", ValueFormat::Byte, 1, 2},
            {"waveform", ValueFormat::Byte, 0, 8},
        }};
        inline constexpr std::array<ValueSpec, 2> PROGRAM_SET_LFO_SYNC_ARGS{{
            {"lfo", ValueFormat::Byte, 1, 1},
            {"enabled", ValueFormat::Byte, 0, 1},
        }};
        inline constexpr std::array<ValueSpec, 2> PROGRAM_SET_LFO_RETRIGGER_ARGS{{
            {"lfo", ValueFormat::Byte, 2, 2},
            {"enabled", ValueFormat::Byte, 0, 1},
        }};
        inline constexpr std::array<ValueSpec, 2> PROGRAM_SET_LFO_RATE_MOD_SOURCE_ARGS{{
            {"lfo", ValueFormat::Byte, 1, 2},
            {"source", ValueFormat::Byte, 0, 14},
        }};
        inline constexpr std::array<ValueSpec, 3> PROGRAM_SET_LFO_RATE_MOD_VALUE_ARGS{{
            {"lfo", ValueFormat::Byte, 1, 2},
            {"sign", ValueFormat::Byte, 0, 1},
            {"magnitude", ValueFormat::Byte, 0, 100},
        }};
        inline constexpr std::array<ValueSpec, 2> PROGRAM_SET_LFO_DELAY_MOD_SOURCE_ARGS{{
            {"lfo", ValueFormat::Byte, 1, 2},
            {"source", ValueFormat::Byte, 0, 14},
        }};
        inline constexpr std::array<ValueSpec, 3> PROGRAM_SET_LFO_DELAY_MOD_VALUE_ARGS{{
            {"lfo", ValueFormat::Byte, 1, 2},
            {"sign", ValueFormat::Byte, 0, 1},
            {"magnitude", ValueFormat::Byte, 0, 100},
        }};
        inline constexpr std::array<ValueSpec, 2> PROGRAM_SET_LFO_DEPTH_MOD_SOURCE_ARGS{{
            {"lfo", ValueFormat::Byte, 1, 2},
            {"source", ValueFormat::Byte, 0, 14},
        }};
        inline constexpr std::array<ValueSpec, 3> PROGRAM_SET_LFO_DEPTH_MOD_VALUE_ARGS{{
            {"lfo", ValueFormat::Byte, 1, 2},
            {"sign", ValueFormat::Byte, 0, 1},
            {"magnitude", ValueFormat::Byte, 0, 100},
        }};
        inline constexpr std::array<ValueSpec, 2> PROGRAM_SET_LFO_MODWHEEL_ARGS{{
            {"lfo", ValueFormat::Byte, 1, 1},
            {"value", ValueFormat::Byte, 0, 100},
        }};
        inline constexpr std::array<ValueSpec, 2> PROGRAM_SET_LFO_AFTERTOUCH_ARGS{{
            {"lfo", ValueFormat::Byte, 1, 1},
            {"value", ValueFormat::Byte, 0, 100},
        }};
        inline constexpr std::array<ValueSpec, 2> PROGRAM_SET_LFO_MIDI_CLOCK_SYNC_ENABLE_ARGS{{
            {"lfo", ValueFormat::Byte, 2, 2},
            {"enabled", ValueFormat::Byte, 0, 1},
        }};
        inline constexpr std::array<ValueSpec, 2> PROGRAM_SET_LFO_MIDI_CLOCK_SYNC_DIVISION_ARGS{{
            {"lfo", ValueFormat::Byte, 2, 2},
            {"division", ValueFormat::Byte, 0, 68},
        }};
        inline constexpr std::array<ValueSpec, 1> PROGRAM_GET_LFO_RATE_ARGS{{
            {"lfo", ValueFormat::Byte, 1, 2},
        }};
        inline constexpr std::array<ValueSpec, 1> PROGRAM_GET_LFO_RATE_REPLY{{
            {"rate", ValueFormat::Byte, 0, 100},
        }};
        inline constexpr std::array<ValueSpec, 1> PROGRAM_GET_LFO_DELAY_ARGS{{
            {"lfo", ValueFormat::Byte, 1, 2},
        }};
        inline constexpr std::array<ValueSpec, 1> PROGRAM_GET_LFO_DELAY_REPLY{{
            {"delay", ValueFormat::Byte, 0, 100},
        }};
        inline constexpr std::array<ValueSpec, 1> PROGRAM_GET_LFO_DEPTH_ARGS{{
            {"lfo", ValueFormat::Byte, 1, 2},
        }};
        inline constexpr std::array<ValueSpec, 1> PROGRAM_GET_LFO_DEPTH_REPLY{{
            {"depth", ValueFormat::Byte, 0, 100},
        }};
        inline constexpr std::array<ValueSpec, 1> PROGRAM_GET_LFO_WAVEFORM_ARGS{{
            {"lfo", ValueFormat::Byte, 1, 2},
        }};
        inline constexpr std::array<ValueSpec, 1> PROGRAM_GET_LFO_WAVEFORM_REPLY{{
            {"waveform", ValueFormat::Byte, 0, 8},
        }};
        inline constexpr std::array<ValueSpec, 1> PROGRAM_GET_LFO_SYNC_ARGS{{
            {"lfo", ValueFormat::Byte, 1, 1},
        }};
        inline constexpr std::array<ValueSpec, 1> PROGRAM_GET_LFO_SYNC_REPLY{{
            {"enabled", ValueFormat::Byte, 0, 1},
        }};
        inline constexpr std::array<ValueSpec, 1> PROGRAM_GET_LFO_RETRIGGER_ARGS{{
            {"lfo", ValueFormat::Byte, 2, 2},
        }};
        inline constexpr std::array<ValueSpec, 1> PROGRAM_GET_LFO_RETRIGGER_REPLY{{
            {"enabled", ValueFormat::Byte, 0, 1},
        }};
        inline constexpr std::array<ValueSpec, 1> PROGRAM_GET_LFO_RATE_MOD_SOURCE_ARGS{{
            {"lfo", ValueFormat::Byte, 1, 2},
        }};
        inline constexpr std::array<ValueSpec, 1> PROGRAM_GET_LFO_RATE_MOD_SOURCE_REPLY{{
            {"source", ValueFormat::Byte, 0, 14},
        }};
        inline constexpr std::array<ValueSpec, 1> PROGRAM_GET_LFO_RATE_MOD_VALUE_ARGS{{
            {"lfo", ValueFormat::Byte, 1, 2},
        }};
        inline constexpr std::array<ValueSpec, 2> PROGRAM_GET_LFO_RATE_MOD_VALUE_REPLY{{
            {"sign", ValueFormat::Byte, 0, 1},
            {"magnitude", ValueFormat::Byte, 0, 100},
        }};
        inline constexpr std::array<ValueSpec, 1> PROGRAM_GET_LFO_DELAY_MOD_SOURCE_ARGS{{
            {"lfo", ValueFormat::Byte, 1, 2},
        }};
        inline constexpr std::array<ValueSpec, 1> PROGRAM_GET_LFO_DELAY_MOD_SOURCE_REPLY{{
            {"source", ValueFormat::Byte, 0, 14},
        }};
        inline constexpr std::array<ValueSpec, 1> PROGRAM_GET_LFO_DELAY_MOD_VALUE_ARGS{{
            {"lfo", ValueFormat::Byte, 1, 2},
        }};
        inline constexpr std::array<ValueSpec, 2> PROGRAM_GET_LFO_DELAY_MOD_VALUE_REPLY{{
            {"sign", ValueFormat::Byte, 0, 1},
            {"magnitude", ValueFormat::Byte, 0, 100},
        }};
        inline constexpr std::array<ValueSpec, 1> PROGRAM_GET_LFO_DEPTH_MOD_SOURCE_ARGS{{
            {"lfo", ValueFormat::Byte, 1, 2},
        }};
        inline constexpr std::array<ValueSpec, 1> PROGRAM_GET_LFO_DEPTH_MOD_SOURCE_REPLY{{
            {"source", ValueFormat::Byte, 0, 14},
        }};
        inline constexpr std::array<ValueSpec, 1> PROGRAM_GET_LFO_DEPTH_MOD_VALUE_ARGS{{
            {"lfo", ValueFormat::Byte, 1, 2},
        }};
        inline constexpr std::array<ValueSpec, 2> PROGRAM_GET_LFO_DEPTH_MOD_VALUE_REPLY{{
            {"sign", ValueFormat::Byte, 0, 1},
            {"magnitude", ValueFormat::Byte, 0, 100},
        }};
        inline constexpr std::array<ValueSpec, 1> PROGRAM_GET_LFO_MODWHEEL_ARGS{{
            {"lfo", ValueFormat::Byte, 1, 1},
        }};
        inline constexpr std::array<ValueSpec, 1> PROGRAM_GET_LFO_MODWHEEL_REPLY{{
            {"value", ValueFormat::Byte, 0, 100},
        }};
        inline constexpr std::array<ValueSpec, 1> PROGRAM_GET_LFO_AFTERTOUCH_ARGS{{
            {"lfo", ValueFormat::Byte, 1, 1},
        }};
        inline constexpr std::array<ValueSpec, 1> PROGRAM_GET_LFO_AFTERTOUCH_REPLY{{
            {"value", ValueFormat::Byte, 0, 100},
        }};
        inline constexpr std::array<ValueSpec, 1> PROGRAM_GET_LFO_MIDI_CLOCK_SYNC_ENABLE_ARGS{{
            {"lfo", ValueFormat::Byte, 2, 2},
        }};
        inline constexpr std::array<ValueSpec, 1> PROGRAM_GET_LFO_MIDI_CLOCK_SYNC_ENABLE_REPLY{{
            {"enabled", ValueFormat::Byte, 0, 1},
        }};
        inline constexpr std::array<ValueSpec, 1> PROGRAM_GET_LFO_MIDI_CLOCK_SYNC_DIVISION_ARGS{{
            {"lfo", ValueFormat::Byte, 2, 2},
        }};
        inline constexpr std::array<ValueSpec, 1> PROGRAM_GET_LFO_MIDI_CLOCK_SYNC_DIVISION_REPLY{{
            {"division", ValueFormat::Byte, 0, 68},
        }};
        inline constexpr std::array<ValueSpec, 2> PROGRAM_SET_PITCH_MOD_SOURCE_ARGS{{
            {"pitchMod", ValueFormat::Byte, 1, 2},
            {"source", ValueFormat::Byte, 0, 14},
        }};
        inline constexpr std::array<ValueSpec, 2> PROGRAM_SET_KEYGROUP_AMP_MOD_SOURCE_ARGS{{
            {"ampMod", ValueFormat::Byte, 1, 1},
            {"source", ValueFormat::Byte, 0, 14},
        }};
        inline constexpr std::array<ValueSpec, 2> PROGRAM_SET_FILTER_MOD_INPUT_SOURCE_ARGS{{
            {"modInput", ValueFormat::Byte, 1, 3},
            {"source", ValueFormat::Byte, 0, 14},
        }};
        inline constexpr std::array<ValueSpec, 1> PROGRAM_GET_PITCH_MOD_SOURCE_ARGS{{
            {"pitchMod", ValueFormat::Byte, 1, 2},
        }};
        inline constexpr std::array<ValueSpec, 1> PROGRAM_GET_PITCH_MOD_SOURCE_REPLY{{
            {"source", ValueFormat::Byte, 0, 14},
        }};
        inline constexpr std::array<ValueSpec, 1> PROGRAM_GET_KEYGROUP_AMP_MOD_SOURCE_ARGS{{
            {"ampMod", ValueFormat::Byte, 1, 1},
        }};
        inline constexpr std::array<ValueSpec, 1> PROGRAM_GET_KEYGROUP_AMP_MOD_SOURCE_REPLY{{
            {"source", ValueFormat::Byte, 0, 14},
        }};
        inline constexpr std::array<ValueSpec, 1> PROGRAM_GET_FILTER_MOD_INPUT_SOURCE_ARGS{{
            {"modInput", ValueFormat::Byte, 1, 3},
        }};
        inline constexpr std::array<ValueSpec, 1> PROGRAM_GET_FILTER_MOD_INPUT_SOURCE_REPLY{{
            {"source", ValueFormat::Byte, 0, 14},
        }};
        inline constexpr std::array<ValueSpec, 2> PROGRAM_SET_NUMBER_ARGS{{
            {"enabled", ValueFormat::Byte, 0, 1},
            {"number", ValueFormat::Byte, 0, 127},
        }};
        inline constexpr std::array<ValueSpec, 1> PROGRAM_ADD_KEYGROUPS_ARGS{{
            {"count", ValueFormat::Byte, 1, 98},
        }};
        inline constexpr std::array<ValueSpec, 1> PROGRAM_DELETE_KEYGROUP_ARGS{{
            {"keygroup", ValueFormat::Byte, 0, 98},
        }};
        inline constexpr std::array<ValueSpec, 1> PROGRAM_SET_CROSSFADE_ARGS{{
            {"enabled", ValueFormat::Byte, 0, 1},
        }};
        inline constexpr std::array<ValueSpec, 2> PROGRAM_GET_NUMBER_REPLY{{
            {"enabled", ValueFormat::Byte, 0, 1},
            {"number", ValueFormat::Byte, 0, 127},
        }};
        inline constexpr std::array<ValueSpec, 1> PROGRAM_GET_KEYGROUP_COUNT_REPLY{{
            {"count", ValueFormat::Byte, 0, 99},
        }};
        inline constexpr std::array<ValueSpec, 1> PROGRAM_GET_CROSSFADE_REPLY{{
            {"enabled", ValueFormat::Byte, 0, 1},
        }};
        inline constexpr std::array<ValueSpec, 2> PROGRAM_GET_INDEX_REPLY{{
            {"indexMsb", ValueFormat::Byte, 0, 127},
            {"indexLsb", ValueFormat::Byte, 0, 127},
        }};
        inline constexpr std::array<ValueSpec, 2> PROGRAM_GET_ALL_NUMBERS_REPLY{{
            {"enabled", ValueFormat::Byte, 0, 1},
            {"number", ValueFormat::Byte, 0, 127},
        }};
        inline constexpr std::array<ValueSpec, 1> PROGRAM_GET_ALL_NAMES_REPLY{{
            {"name", ValueFormat::String, 0, 20},
        }};
        inline constexpr std::array<ValueSpec, 1> KEYGROUP_SELECT_ARGS{{
            {"keygroup", ValueFormat::Byte, 0, 99},
        }};
        inline constexpr std::array<ValueSpec, 1> KEYGROUP_GET_CURRENT_REPLY{{
            {"keygroup", ValueFormat::Byte, 0, 99},
        }};
        inline constexpr std::array<ValueSpec, 1> KEYGROUP_SET_LOW_NOTE_ARGS{{
            {"note", ValueFormat::Byte, 21, 127},
        }};
        inline constexpr std::array<ValueSpec, 1> KEYGROUP_SET_HIGH_NOTE_ARGS{{
            {"note", ValueFormat::Byte, 21, 127},
        }};
        inline constexpr std::array<ValueSpec, 1> KEYGROUP_SET_MUTE_GROUP_ARGS{{
            {"muteGroup", ValueFormat::Byte, 0, 32},
        }};
        inline constexpr std::array<ValueSpec, 1> KEYGROUP_SET_FX_OVERRIDE_ARGS{{
            {"fx", ValueFormat::Byte, 0, 4},
        }};
        inline constexpr std::array<ValueSpec, 1> KEYGROUP_SET_FX_SEND_LEVEL_ARGS{{
            {"level", ValueFormat::Byte, 0, 100},
        }};
        inline constexpr std::array<ValueSpec, 1> KEYGROUP_SET_ZONE_CROSSFADE_ARGS{{
            {"enabled", ValueFormat::Byte, 0, 1},
        }};
        inline constexpr std::array<ValueSpec, 1> KEYGROUP_GET_LOW_NOTE_REPLY{{
            {"note", ValueFormat::Byte, 21, 127},
        }};
        inline constexpr std::array<ValueSpec, 1> KEYGROUP_GET_HIGH_NOTE_REPLY{{
            {"note", ValueFormat::Byte, 21, 127},
        }};
        inline constexpr std::array<ValueSpec, 1> KEYGROUP_GET_MUTE_GROUP_REPLY{{
            {"muteGroup", ValueFormat::Byte, 0, 32},
        }};
        inline constexpr std::array<ValueSpec, 1> KEYGROUP_GET_FX_OVERRIDE_REPLY{{
            {"fx", ValueFormat::Byte, 0, 4},
        }};
        inline constexpr std::array<ValueSpec, 1> KEYGROUP_GET_FX_SEND_LEVEL_REPLY{{
            {"level", ValueFormat::Byte, 0, 100},
        }};
        inline constexpr std::array<ValueSpec, 1> KEYGROUP_GET_ZONE_CROSSFADE_REPLY{{
            {"enabled", ValueFormat::Byte, 0, 1},
        }};
        inline constexpr std::array<ValueSpec, 2> KEYGROUP_SET_SEMITONE_TUNE_ARGS{{
            {"sign", ValueFormat::Byte, 0, 1},
            {"magnitude", ValueFormat::Byte, 0, 36},
        }};
        inline constexpr std::array<ValueSpec, 2> KEYGROUP_SET_FINE_TUNE_ARGS{{
            {"sign", ValueFormat::Byte, 0, 1},
            {"magnitude", ValueFormat::Byte, 0, 50},
        }};
        inline constexpr std::array<ValueSpec, 1> KEYGROUP_SET_LEVEL_ARGS{{
            {"value", ValueFormat::Byte, 0, 10},
        }};
        inline constexpr std::array<ValueSpec, 3> KEYGROUP_SET_PITCH_MOD_VALUE_ARGS{{
            {"pitchMod", ValueFormat::Byte, 1, 2},
            {"sign", ValueFormat::Byte, 0, 1},
            {"magnitude", ValueFormat::Byte, 0, 100},
        }};
        inline constexpr std::array<ValueSpec, 3> KEYGROUP_SET_AMP_MOD_VALUE_ARGS{{
            {"ampMod", ValueFormat::Byte, 1, 1},
            {"sign", ValueFormat::Byte, 0, 1},
            {"magnitude", ValueFormat::Byte, 0, 100},
        }};
        inline constexpr std::array<ValueSpec, 2> KEYGROUP_GET_SEMITONE_TUNE_REPLY{{
            {"sign", ValueFormat::Byte, 0, 1},
            {"magnitude", ValueFormat::Byte, 0, 36},
        }};
        inline constexpr std::array<ValueSpec, 2> KEYGROUP_GET_FINE_TUNE_REPLY{{
            {"sign", ValueFormat::Byte, 0, 1},
            {"magnitude", ValueFormat::Byte, 0, 50},
        }};
        inline constexpr std::array<ValueSpec, 1> KEYGROUP_GET_LEVEL_REPLY{{
            {"value", ValueFormat::Byte, 0, 10},
        }};
        inline constexpr std::array<ValueSpec, 1> KEYGROUP_GET_PITCH_MOD_VALUE_ARGS{{
            {"pitchMod", ValueFormat::Byte, 1, 2},
        }};
        inline constexpr std::array<ValueSpec, 2> KEYGROUP_GET_PITCH_MOD_VALUE_REPLY{{
            {"sign", ValueFormat::Byte, 0, 1},
            {"magnitude", ValueFormat::Byte, 0, 100},
        }};
        inline constexpr std::array<ValueSpec, 1> KEYGROUP_GET_AMP_MOD_VALUE_ARGS{{
            {"ampMod", ValueFormat::Byte, 1, 1},
        }};
        inline constexpr std::array<ValueSpec, 2> KEYGROUP_GET_AMP_MOD_VALUE_REPLY{{
            {"sign", ValueFormat::Byte, 0, 1},
            {"magnitude", ValueFormat::Byte, 0, 100},
        }};
        inline constexpr std::array<ValueSpec, 1> KEYGROUP_SET_FILTER_MODE_ARGS{{
            {"mode", ValueFormat::Byte, 0, 25},
        }};
        inline constexpr std::array<ValueSpec, 1> KEYGROUP_SET_FILTER_CUTOFF_ARGS{{
            {"value", ValueFormat::Byte, 0, 100},
        }};
        inline constexpr std::array<ValueSpec, 1> KEYGROUP_SET_FILTER_RESONANCE_ARGS{{
            {"value", ValueFormat::Byte, 0, 15},
        }};
        inline constexpr std::array<ValueSpec, 2> KEYGROUP_SET_FILTER_KEYBOARD_TRACK_ARGS{{
            {"sign", ValueFormat::Byte, 0, 1},
            {"magnitude", ValueFormat::Byte, 0, 36},
        }};
        inline constexpr std::array<ValueSpec, 3> KEYGROUP_SET_FILTER_MOD_INPUT_VALUE_ARGS{{
            {"modInput", ValueFormat::Byte, 1, 3},
            {"sign", ValueFormat::Byte, 0, 1},
            {"magnitude", ValueFormat::Byte, 0, 100},
        }};
        inline constexpr std::array<ValueSpec, 1> KEYGROUP_SET_FILTER_ATTENUATION_ARGS{{
            {"value", ValueFormat::Byte, 0, 5},
        }};
        inline constexpr std::array<ValueSpec, 1> KEYGROUP_GET_FILTER_MODE_REPLY{{
            {"mode", ValueFormat::Byte, 0, 25},
        }};
        inline constexpr std::array<ValueSpec, 1> KEYGROUP_GET_FILTER_CUTOFF_REPLY{{
            {"value", ValueFormat::Byte, 0, 100},
        }};
        inline constexpr std::array<ValueSpec, 1> KEYGROUP_GET_FILTER_RESONANCE_REPLY{{
            {"value", ValueFormat::Byte, 0, 15},
        }};
        inline constexpr std::array<ValueSpec, 2> KEYGROUP_GET_FILTER_KEYBOARD_TRACK_REPLY{{
            {"sign", ValueFormat::Byte, 0, 1},
            {"magnitude", ValueFormat::Byte, 0, 36},
        }};
        inline constexpr std::array<ValueSpec, 1> KEYGROUP_GET_FILTER_MOD_INPUT_VALUE_ARGS{{
            {"modInput", ValueFormat::Byte, 1, 3},
        }};
        inline constexpr std::array<ValueSpec, 2> KEYGROUP_GET_FILTER_MOD_INPUT_VALUE_REPLY{{
            {"sign", ValueFormat::Byte, 0, 1},
            {"magnitude", ValueFormat::Byte, 0, 100},
        }};
        inline constexpr std::array<ValueSpec, 1> KEYGROUP_GET_FILTER_ATTENUATION_REPLY{{
            {"value", ValueFormat::Byte, 0, 5},
        }};
        inline constexpr std::array<ValueSpec, 1> KEYGROUP_SET_FILTER_ENV_ATTACK_ARGS{{
            {"value", ValueFormat::Byte, 0, 100},
        }};
        inline constexpr std::array<ValueSpec, 2> KEYGROUP_SET_FILTER_ENV_VELOCITY_TO_ATTACK_ARGS{{
            {"sign", ValueFormat::Byte, 0, 1},
            {"magnitude", ValueFormat::Byte, 0, 100},
        }};
        inline constexpr std::array<ValueSpec, 1> KEYGROUP_SET_FILTER_ENV_DECAY_ARGS{{
            {"value", ValueFormat::Byte, 0, 100},
        }};
        inline constexpr std::array<ValueSpec, 1> KEYGROUP_SET_FILTER_ENV_SUSTAIN_ARGS{{
            {"value", ValueFormat::Byte, 0, 100},
        }};
        inline constexpr std::array<ValueSpec, 1> KEYGROUP_SET_FILTER_ENV_RELEASE_ARGS{{
            {"value", ValueFormat::Byte, 0, 100},
        }};
        inline constexpr std::array<ValueSpec, 2> KEYGROUP_SET_FILTER_ENV_ON_VELOCITY_TO_RELEASE_ARGS{{
            {"sign", ValueFormat::Byte, 0, 1},
            {"magnitude", ValueFormat::Byte, 0, 100},
        }};
        inline constexpr std::array<ValueSpec, 2> KEYGROUP_SET_FILTER_ENV_KEYSCALE_ARGS{{
            {"sign", ValueFormat::Byte, 0, 1},
            {"magnitude", ValueFormat::Byte, 0, 100},
        }};
        inline constexpr std::array<ValueSpec, 2> KEYGROUP_SET_FILTER_ENV_DEPTH_ARGS{{
            {"sign", ValueFormat::Byte, 0, 1},
            {"magnitude", ValueFormat::Byte, 0, 100},
        }};
        inline constexpr std::array<ValueSpec, 2> KEYGROUP_SET_FILTER_ENV_OFF_VELOCITY_TO_RELEASE_ARGS{{
            {"sign", ValueFormat::Byte, 0, 1},
            {"magnitude", ValueFormat::Byte, 0, 100},
        }};
        inline constexpr std::array<ValueSpec, 1> KEYGROUP_GET_FILTER_ENV_ATTACK_REPLY{{
            {"value", ValueFormat::Byte, 0, 100},
        }};
        inline constexpr std::array<ValueSpec, 2> KEYGROUP_GET_FILTER_ENV_VELOCITY_TO_ATTACK_REPLY{{
            {"sign", ValueFormat::Byte, 0, 1},
            {"magnitude", ValueFormat::Byte, 0, 100},
        }};
        inline constexpr std::array<ValueSpec, 1> KEYGROUP_GET_FILTER_ENV_DECAY_REPLY{{
            {"value", ValueFormat::Byte, 0, 100},
        }};
        inline constexpr std::array<ValueSpec, 1> KEYGROUP_GET_FILTER_ENV_SUSTAIN_REPLY{{
            {"value", ValueFormat::Byte, 0, 100},
        }};
        inline constexpr std::array<ValueSpec, 1> KEYGROUP_GET_FILTER_ENV_RELEASE_REPLY{{
            {"value", ValueFormat::Byte, 0, 100},
        }};
        inline constexpr std::array<ValueSpec, 2> KEYGROUP_GET_FILTER_ENV_ON_VELOCITY_TO_RELEASE_REPLY{{
            {"sign", ValueFormat::Byte, 0, 1},
            {"magnitude", ValueFormat::Byte, 0, 100},
        }};
        inline constexpr std::array<ValueSpec, 2> KEYGROUP_GET_FILTER_ENV_KEYSCALE_REPLY{{
            {"sign", ValueFormat::Byte, 0, 1},
            {"magnitude", ValueFormat::Byte, 0, 100},
        }};
        inline constexpr std::array<ValueSpec, 2> KEYGROUP_GET_FILTER_ENV_DEPTH_REPLY{{
            {"sign", ValueFormat::Byte, 0, 1},
            {"magnitude", ValueFormat::Byte, 0, 100},
        }};
        inline constexpr std::array<ValueSpec, 2> KEYGROUP_GET_FILTER_ENV_OFF_VELOCITY_TO_RELEASE_REPLY{{
            {"sign", ValueFormat::Byte, 0, 1},
            {"magnitude", ValueFormat::Byte, 0, 100},
        }};
        inline constexpr std::array<ValueSpec, 1> KEYGROUP_SET_AMP_ENV_ATTACK_ARGS{{
            {"value", ValueFormat::Byte, 0, 100},
        }};
        inline constexpr std::array<ValueSpec, 2> KEYGROUP_SET_AMP_ENV_VELOCITY_TO_ATTACK_ARGS{{
            {"sign", ValueFormat::Byte, 0, 1},
            {"magnitude", ValueFormat::Byte, 0, 100},
        }};
        inline constexpr std::array<ValueSpec, 1> KEYGROUP_SET_AMP_ENV_DECAY_ARGS{{
            {"value", ValueFormat::Byte, 0, 100},
        }};
        inline constexpr std::array<ValueSpec, 1> KEYGROUP_SET_AMP_ENV_SUSTAIN_ARGS{{
            {"value", ValueFormat::Byte, 0, 100},
        }};
        inline constexpr std::array<ValueSpec, 1> KEYGROUP_SET_AMP_ENV_RELEASE_ARGS{{
            {"value", ValueFormat::Byte, 0, 100},
        }};
        inline constexpr std::array<ValueSpec, 2> KEYGROUP_SET_AMP_ENV_ON_VELOCITY_TO_RELEASE_ARGS{{
            {"sign", ValueFormat::Byte, 0, 1},
            {"magnitude", ValueFormat::Byte, 0, 100},
        }};
        inline constexpr std::array<ValueSpec, 2> KEYGROUP_SET_AMP_ENV_KEYSCALE_ARGS{{
            {"sign", ValueFormat::Byte, 0, 1},
            {"magnitude", ValueFormat::Byte, 0, 100},
        }};
        inline constexpr std::array<ValueSpec, 2> KEYGROUP_SET_AMP_ENV_OFF_VELOCITY_TO_RELEASE_ARGS{{
            {"sign", ValueFormat::Byte, 0, 1},
            {"magnitude", ValueFormat::Byte, 0, 100},
        }};
        inline constexpr std::array<ValueSpec, 1> KEYGROUP_GET_AMP_ENV_ATTACK_REPLY{{
            {"value", ValueFormat::Byte, 0, 100},
        }};
        inline constexpr std::array<ValueSpec, 2> KEYGROUP_GET_AMP_ENV_VELOCITY_TO_ATTACK_REPLY{{
            {"sign", ValueFormat::Byte, 0, 1},
            {"magnitude", ValueFormat::Byte, 0, 100},
        }};
        inline constexpr std::array<ValueSpec, 1> KEYGROUP_GET_AMP_ENV_DECAY_REPLY{{
            {"value", ValueFormat::Byte, 0, 100},
        }};
        inline constexpr std::array<ValueSpec, 1> KEYGROUP_GET_AMP_ENV_SUSTAIN_REPLY{{
            {"value", ValueFormat::Byte, 0, 100},
        }};
        inline constexpr std::array<ValueSpec, 1> KEYGROUP_GET_AMP_ENV_RELEASE_REPLY{{
            {"value", ValueFormat::Byte, 0, 100},
        }};
        inline constexpr std::array<ValueSpec, 2> KEYGROUP_GET_AMP_ENV_ON_VELOCITY_TO_RELEASE_REPLY{{
            {"sign", ValueFormat::Byte, 0, 1},
            {"magnitude", ValueFormat::Byte, 0, 100},
        }};
        inline constexpr std::array<ValueSpec, 2> KEYGROUP_GET_AMP_ENV_KEYSCALE_REPLY{{
            {"sign", ValueFormat::Byte, 0, 1},
            {"magnitude", ValueFormat::Byte, 0, 100},
        }};
        inline constexpr std::array<ValueSpec, 2> KEYGROUP_GET_AMP_ENV_OFF_VELOCITY_TO_RELEASE_REPLY{{
            {"sign", ValueFormat::Byte, 0, 1},
            {"magnitude", ValueFormat::Byte, 0, 100},
        }};
        inline constexpr std::array<ValueSpec, 2> KEYGROUP_SET_AUX_ENV_RATE_ARGS{{
            {"auxRate", ValueFormat::Byte, 1, 4},
            {"value", ValueFormat::Byte, 0, 100},
        }};
        inline constexpr std::array<ValueSpec, 3> KEYGROUP_SET_AUX_ENV_VELOCITY_TO_RATE_ARGS{{
            {"auxRate", ValueFormat::Byte, 1, 4},
            {"sign", ValueFormat::Byte, 0, 1},
            {"magnitude", ValueFormat::Byte, 0, 100},
        }};
        inline constexpr std::array<ValueSpec, 2> KEYGROUP_SET_AUX_ENV_KEYBOARD_TO_R2_R4_ARGS{{
            {"sign", ValueFormat::Byte, 0, 1},
            {"magnitude", ValueFormat::Byte, 0, 100},
        }};
        inline constexpr std::array<ValueSpec, 2> KEYGROUP_SET_AUX_ENV_LEVEL_ARGS{{
            {"auxLevel", ValueFormat::Byte, 1, 4},
            {"value", ValueFormat::Byte, 0, 100},
        }};
        inline constexpr std::array<ValueSpec, 3> KEYGROUP_SET_AUX_ENV_OFF_VELOCITY_TO_RATE_ARGS{{
            {"auxRate", ValueFormat::Byte, 4, 4},
            {"sign", ValueFormat::Byte, 0, 1},
            {"magnitude", ValueFormat::Byte, 0, 100},
        }};
        inline constexpr std::array<ValueSpec, 1> KEYGROUP_GET_AUX_ENV_RATE_ARGS{{
            {"auxRate", ValueFormat::Byte, 1, 4},
        }};
        inline constexpr std::array<ValueSpec, 1> KEYGROUP_GET_AUX_ENV_RATE_REPLY{{
            {"value", ValueFormat::Byte, 0, 100},
        }};
        inline constexpr std::array<ValueSpec, 1> KEYGROUP_GET_AUX_ENV_VELOCITY_TO_RATE_ARGS{{
            {"auxRate", ValueFormat::Byte, 1, 4},
        }};
        inline constexpr std::array<ValueSpec, 2> KEYGROUP_GET_AUX_ENV_VELOCITY_TO_RATE_REPLY{{
            {"sign", ValueFormat::Byte, 0, 1},
            {"magnitude", ValueFormat::Byte, 0, 100},
        }};
        inline constexpr std::array<ValueSpec, 2> KEYGROUP_GET_AUX_ENV_KEYBOARD_TO_R2_R4_REPLY{{
            {"sign", ValueFormat::Byte, 0, 1},
            {"magnitude", ValueFormat::Byte, 0, 100},
        }};
        inline constexpr std::array<ValueSpec, 1> KEYGROUP_GET_AUX_ENV_LEVEL_ARGS{{
            {"auxLevel", ValueFormat::Byte, 1, 4},
        }};
        inline constexpr std::array<ValueSpec, 1> KEYGROUP_GET_AUX_ENV_LEVEL_REPLY{{
            {"value", ValueFormat::Byte, 0, 100},
        }};
        inline constexpr std::array<ValueSpec, 1> KEYGROUP_GET_AUX_ENV_OFF_VELOCITY_TO_RATE_ARGS{{
            {"auxRate", ValueFormat::Byte, 4, 4},
        }};
        inline constexpr std::array<ValueSpec, 2> KEYGROUP_GET_AUX_ENV_OFF_VELOCITY_TO_RATE_REPLY{{
            {"sign", ValueFormat::Byte, 0, 1},
            {"magnitude", ValueFormat::Byte, 0, 100},
        }};
        inline constexpr std::array<ValueSpec, 2> ZONE_SET_SAMPLE_ARGS{{
            {"zone", ValueFormat::Byte, 0, 4},
            {"name", ValueFormat::String, 0, 255},
        }};
        inline constexpr std::array<ValueSpec, 3> ZONE_SET_LEVEL_ARGS{{
            {"zone", ValueFormat::Byte, 0, 4},
            {"sign", ValueFormat::Byte, 0, 1},
            {"magnitude", ValueFormat::Byte, 0, 100},
        }};
        inline constexpr std::array<ValueSpec, 2> ZONE_SET_PAN_BALANCE_ARGS{{
            {"zone", ValueFormat::Byte, 0, 4},
            {"panBalance", ValueFormat::Byte, 14, 114},
        }};
        inline constexpr std::array<ValueSpec, 2> ZONE_SET_OUTPUT_ARGS{{
            {"zone", ValueFormat::Byte, 0, 4},
            {"output", ValueFormat::Byte, 0, 24},
        }};
        inline constexpr std::array<ValueSpec, 3> ZONE_SET_FILTER_ARGS{{
            {"zone", ValueFormat::Byte, 0, 4},
            {"sign", ValueFormat::Byte, 0, 1},
            {"magnitude", ValueFormat::Byte, 0, 100},
        }};
        inline constexpr std::array<ValueSpec, 3> ZONE_SET_FINE_TUNE_ARGS{{
            {"zone", ValueFormat::Byte, 0, 4},
            {"sign", ValueFormat::Byte, 0, 1},
            {"magnitude", ValueFormat::Byte, 0, 50},
        }};
        inline constexpr std::array<ValueSpec, 3> ZONE_SET_SEMITONE_TUNE_ARGS{{
            {"zone", ValueFormat::Byte, 0, 4},
            {"sign", ValueFormat::Byte, 0, 1},
            {"magnitude", ValueFormat::Byte, 0, 36},
        }};
        inline constexpr std::array<ValueSpec, 2> ZONE_SET_KEYBOARD_TRACK_ARGS{{
            {"zone", ValueFormat::Byte, 0, 4},
            {"value", ValueFormat::Byte, 0, 1},
        }};
        inline constexpr std::array<ValueSpec, 2> ZONE_SET_PLAYBACK_ARGS{{
            {"zone", ValueFormat::Byte, 0, 4},
            {"mode", ValueFormat::Byte, 0, 6},
        }};
        inline constexpr std::array<ValueSpec, 4> ZONE_SET_VELOCITY_TO_START_ARGS{{
            {"zone", ValueFormat::Byte, 0, 4},
            {"sign", ValueFormat::Byte, 0, 1},
            {"magnitudeMsb", ValueFormat::Byte, 0, 127},
            {"magnitudeLsb", ValueFormat::Byte, 0, 127},
        }};
        inline constexpr std::array<ValueSpec, 2> ZONE_SET_HIGH_VELOCITY_ARGS{{
            {"zone", ValueFormat::Byte, 0, 4},
            {"velocity", ValueFormat::Byte, 0, 127},
        }};
        inline constexpr std::array<ValueSpec, 2> ZONE_SET_LOW_VELOCITY_ARGS{{
            {"zone", ValueFormat::Byte, 0, 4},
            {"velocity", ValueFormat::Byte, 0, 127},
        }};
        inline constexpr std::array<ValueSpec, 2> ZONE_SET_MUTE_ARGS{{
            {"zone", ValueFormat::Byte, 0, 4},
            {"value", ValueFormat::Byte, 0, 1},
        }};
        inline constexpr std::array<ValueSpec, 2> ZONE_SET_SOLO_ARGS{{
            {"zone", ValueFormat::Byte, 0, 4},
            {"value", ValueFormat::Byte, 0, 1},
        }};
        inline constexpr std::array<ValueSpec, 1> ZONE_GET_SAMPLE_ARGS{{
            {"zone", ValueFormat::Byte, 0, 4},
        }};
        inline constexpr std::array<ValueSpec, 1> ZONE_GET_SAMPLE_REPLY{{
            {"name", ValueFormat::String, 0, 255},
        }};
        inline constexpr std::array<ValueSpec, 1> ZONE_GET_LEVEL_ARGS{{
            {"zone", ValueFormat::Byte, 0, 4},
        }};
        inline constexpr std::array<ValueSpec, 2> ZONE_GET_LEVEL_REPLY{{
            {"sign", ValueFormat::Byte, 0, 1},
            {"magnitude", ValueFormat::Byte, 0, 100},
        }};
        inline constexpr std::array<ValueSpec, 1> ZONE_GET_PAN_BALANCE_ARGS{{
            {"zone", ValueFormat::Byte, 0, 4},
        }};
        inline constexpr std::array<ValueSpec, 1> ZONE_GET_PAN_BALANCE_REPLY{{
            {"panBalance", ValueFormat::Byte, 14, 114},
        }};
        inline constexpr std::array<ValueSpec, 1> ZONE_GET_OUTPUT_ARGS{{
            {"zone", ValueFormat::Byte, 0, 4},
        }};
        inline constexpr std::array<ValueSpec, 1> ZONE_GET_OUTPUT_REPLY{{
            {"output", ValueFormat::Byte, 0, 24},
        }};
        inline constexpr std::array<ValueSpec, 1> ZONE_GET_FILTER_ARGS{{
            {"zone", ValueFormat::Byte, 0, 4},
        }};
        inline constexpr std::array<ValueSpec, 2> ZONE_GET_FILTER_REPLY{{
            {"sign", ValueFormat::Byte, 0, 1},
            {"magnitude", ValueFormat::Byte, 0, 100},
        }};
        inline constexpr std::array<ValueSpec, 1> ZONE_GET_FINE_TUNE_ARGS{{
            {"zone", ValueFormat::Byte, 0, 4},
        }};
        inline constexpr std::array<ValueSpec, 2> ZONE_GET_FINE_TUNE_REPLY{{
            {"sign", ValueFormat::Byte, 0, 1},
            {"magnitude", ValueFormat::Byte, 0, 50},
        }};
        inline constexpr std::array<ValueSpec, 1> ZONE_GET_SEMITONE_TUNE_ARGS{{
            {"zone", ValueFormat::Byte, 0, 4},
        }};
        inline constexpr std::array<ValueSpec, 2> ZONE_GET_SEMITONE_TUNE_REPLY{{
            {"sign", ValueFormat::Byte, 0, 1},
            {"magnitude", ValueFormat::Byte, 0, 36},
        }};
        inline constexpr std::array<ValueSpec, 1> ZONE_GET_KEYBOARD_TRACK_ARGS{{
            {"zone", ValueFormat::Byte, 0, 4},
        }};
        inline constexpr std::array<ValueSpec, 1> ZONE_GET_KEYBOARD_TRACK_REPLY{{
            {"value", ValueFormat::Byte, 0, 1},
        }};
        inline constexpr std::array<ValueSpec, 1> ZONE_GET_PLAYBACK_ARGS{{
            {"zone", ValueFormat::Byte, 0, 4},
        }};
        inline constexpr std::array<ValueSpec, 1> ZONE_GET_PLAYBACK_REPLY{{
            {"mode", ValueFormat::Byte, 0, 6},
        }};
        inline constexpr std::array<ValueSpec, 1> ZONE_GET_VELOCITY_TO_START_ARGS{{
            {"zone", ValueFormat::Byte, 0, 4},
        }};
        inline constexpr std::array<ValueSpec, 3> ZONE_GET_VELOCITY_TO_START_REPLY{{
            {"sign", ValueFormat::Byte, 0, 1},
            {"magnitudeMsb", ValueFormat::Byte, 0, 127},
            {"magnitudeLsb", ValueFormat::Byte, 0, 127},
        }};
        inline constexpr std::array<ValueSpec, 1> ZONE_GET_HIGH_VELOCITY_ARGS{{
            {"zone", ValueFormat::Byte, 0, 4},
        }};
        inline constexpr std::array<ValueSpec, 1> ZONE_GET_HIGH_VELOCITY_REPLY{{
            {"velocity", ValueFormat::Byte, 0, 127},
        }};
        inline constexpr std::array<ValueSpec, 1> ZONE_GET_LOW_VELOCITY_ARGS{{
            {"zone", ValueFormat::Byte, 0, 4},
        }};
        inline constexpr std::array<ValueSpec, 1> ZONE_GET_LOW_VELOCITY_REPLY{{
            {"velocity", ValueFormat::Byte, 0, 127},
        }};
        inline constexpr std::array<ValueSpec, 1> ZONE_GET_MUTE_ARGS{{
            {"zone", ValueFormat::Byte, 0, 4},
        }};
        inline constexpr std::array<ValueSpec, 1> ZONE_GET_MUTE_REPLY{{
            {"value", ValueFormat::Byte, 0, 1},
        }};
        inline constexpr std::array<ValueSpec, 1> ZONE_GET_SOLO_ARGS{{
            {"zone", ValueFormat::Byte, 0, 4},
        }};
        inline constexpr std::array<ValueSpec, 1> ZONE_GET_SOLO_REPLY{{
            {"value", ValueFormat::Byte, 0, 1},
        }};
        inline constexpr std::array<ValueSpec, 1> SAMPLE_SELECT_BY_NAME_ARGS{{
            {"name", ValueFormat::String, 0, 255},
        }};
        inline constexpr std::array<ValueSpec, 2> SAMPLE_SELECT_BY_INDEX_ARGS{{
            {"indexMsb", ValueFormat::Byte, 0, 127},
            {"indexLsb", ValueFormat::Byte, 0, 127},
        }};
        inline constexpr std::array<ValueSpec, 1> SAMPLE_RENAME_CURRENT_ARGS{{
            {"name", ValueFormat::String, 0, 255},
        }};
        inline constexpr std::array<ValueSpec, 2> SAMPLE_GET_CURRENT_INDEX_REPLY{{
            {"indexMsb", ValueFormat::Byte, 0, 127},
            {"indexLsb", ValueFormat::Byte, 0, 127},
        }};
        inline constexpr std::array<ValueSpec, 1> SAMPLE_GET_CURRENT_NAME_REPLY{{
            {"name", ValueFormat::String, 0, 255},
        }};
    }

    /// Every record of the data file, indexed by ItemId.
    inline constexpr std::array<ItemDescriptor, 221> ITEM_TABLE{{
        // section 00 item 00 [RQ-AKM-012]
        {"Query", 0x00, 0x00, ItemKind::Set, {}, {}},
        // section 00 item 01 [RQ-AKM-014]
        {"Notification", 0x00, 0x01, ItemKind::Set, item_data::SYS_EX_NOTIFICATION_ARGS, {}},
        // section 00 item 03 [RQ-AKM-014]
        {"Sync LCD", 0x00, 0x03, ItemKind::Set, item_data::SYS_EX_SYNC_LCD_ARGS, {}},
        // section 00 item 04 [RQ-AKM-013]
        {"Checksum verification", 0x00, 0x04, ItemKind::Set, item_data::SYS_EX_CHECKSUM_ARGS, {}},
        // section 00 item 05 [RQ-AKM-014]
        {"Auto screen update", 0x00, 0x05, ItemKind::Set, item_data::SYS_EX_AUTO_SCREEN_UPDATE_ARGS, {}},
        // section 00 item 06 [RQ-AKM-015]
        {"Echo", 0x00, 0x06, ItemKind::Get, item_data::SYS_EX_ECHO_ARGS, item_data::SYS_EX_ECHO_REPLY},
        // section 00 item 07 [RQ-AKM-011, RQ-AKM-014]
        {"Still Alive monitor", 0x00, 0x07, ItemKind::Set, item_data::SYS_EX_STILL_ALIVE_ARGS, {}},
        // section 02 item 00 [RQ-AKM-044]
        {"Operating system version", 0x02, 0x00, ItemKind::Get, {}, item_data::SYSTEM_OS_VERSION_REPLY},
        // section 02 item 01 [RQ-AKM-044]
        {"Operating system sub-version", 0x02, 0x01, ItemKind::Get, {}, item_data::SYSTEM_OS_SUB_VERSION_REPLY},
        // section 0A item 02 [RQ-AKM-021]
        {"Create Program", 0x0A, 0x02, ItemKind::Set, item_data::PROGRAM_CREATE_ARGS, {}},
        // section 0A item 03 [RQ-AKM-021]
        {"Create Program with keygroups", 0x0A, 0x03, ItemKind::Set, item_data::PROGRAM_CREATE_WITH_KEYGROUPS_ARGS, {}},
        // section 0A item 05 [RQ-AKM-021]
        {"Select Program by name", 0x0A, 0x05, ItemKind::Set, item_data::PROGRAM_SELECT_BY_NAME_ARGS, {}},
        // section 0A item 06 [RQ-AKM-021]
        {"Select Program by index", 0x0A, 0x06, ItemKind::Set, item_data::PROGRAM_SELECT_BY_INDEX_ARGS, {}},
        // section 0A item 08 [RQ-AKM-021]
        {"Delete the currently selected Program", 0x0A, 0x08, ItemKind::Set, {}, {}},
        // section 0A item 09 [RQ-AKM-021]
        {"Rename currently selected Program", 0x0A, 0x09, ItemKind::Set, item_data::PROGRAM_RENAME_CURRENT_ARGS, {}},
        // section 0A item 10 [RQ-AKM-021, RQ-AKM-023]
        {"Get Number of Programs in memory", 0x0A, 0x10, ItemKind::Get, {}, item_data::PROGRAM_GET_COUNT_REPLY},
        // section 0A item 13 [RQ-AKM-021, RQ-AKM-023]
        {"Get Current Program Name", 0x0A, 0x13, ItemKind::Get, {}, item_data::PROGRAM_GET_CURRENT_NAME_REPLY},
        // section 0A item 20 [RQ-AKM-024]
        {"Set Loudness", 0x0A, 0x20, ItemKind::Set, item_data::PROGRAM_SET_LOUDNESS_ARGS, {}},
        // section 0A item 21 [RQ-AKM-024]
        {"Set Velocity Sensitivity", 0x0A, 0x21, ItemKind::Set, item_data::PROGRAM_SET_VELOCITY_SENSITIVITY_ARGS, {}},
        // section 0A item 22 [RQ-AKM-024]
        {"Set Amp Mod Source", 0x0A, 0x22, ItemKind::Set, item_data::PROGRAM_SET_AMP_MOD_SOURCE_ARGS, {}},
        // section 0A item 23 [RQ-AKM-024]
        {"Set Amp Mod Value", 0x0A, 0x23, ItemKind::Set, item_data::PROGRAM_SET_AMP_MOD_VALUE_ARGS, {}},
        // section 0A item 24 [RQ-AKM-024]
        {"Set Pan Mod Source", 0x0A, 0x24, ItemKind::Set, item_data::PROGRAM_SET_PAN_MOD_SOURCE_ARGS, {}},
        // section 0A item 25 [RQ-AKM-024]
        {"Set Pan Mod Value", 0x0A, 0x25, ItemKind::Set, item_data::PROGRAM_SET_PAN_MOD_VALUE_ARGS, {}},
        // section 0A item 28 [RQ-AKM-024]
        {"Get Loudness", 0x0A, 0x28, ItemKind::Get, {}, item_data::PROGRAM_GET_LOUDNESS_REPLY},
        // section 0A item 29 [RQ-AKM-024]
        {"Get Velocity Sensitivity", 0x0A, 0x29, ItemKind::Get, {}, item_data::PROGRAM_GET_VELOCITY_SENSITIVITY_REPLY},
        // section 0A item 2A [RQ-AKM-024]
        {"Get Amp Mod Source", 0x0A, 0x2A, ItemKind::Get, item_data::PROGRAM_GET_AMP_MOD_SOURCE_ARGS, item_data::PROGRAM_GET_AMP_MOD_SOURCE_REPLY},
        // section 0A item 2B [RQ-AKM-024]
        {"Get Amp Mod Value", 0x0A, 0x2B, ItemKind::Get, item_data::PROGRAM_GET_AMP_MOD_VALUE_ARGS, item_data::PROGRAM_GET_AMP_MOD_VALUE_REPLY},
        // section 0A item 2C [RQ-AKM-024]
        {"Get Pan Mod Source", 0x0A, 0x2C, ItemKind::Get, item_data::PROGRAM_GET_PAN_MOD_SOURCE_ARGS, item_data::PROGRAM_GET_PAN_MOD_SOURCE_REPLY},
        // section 0A item 2D [RQ-AKM-024]
        {"Get Pan Mod Value", 0x0A, 0x2D, ItemKind::Get, item_data::PROGRAM_GET_PAN_MOD_VALUE_ARGS, item_data::PROGRAM_GET_PAN_MOD_VALUE_REPLY},
        // section 0A item 30 [RQ-AKM-024]
        {"Set Semitone Tune", 0x0A, 0x30, ItemKind::Set, item_data::PROGRAM_SET_SEMITONE_TUNE_ARGS, {}},
        // section 0A item 31 [RQ-AKM-024]
        {"Set Fine Tune", 0x0A, 0x31, ItemKind::Set, item_data::PROGRAM_SET_FINE_TUNE_ARGS, {}},
        // section 0A item 32 [RQ-AKM-024]
        {"Set Tune Template", 0x0A, 0x32, ItemKind::Set, item_data::PROGRAM_SET_TUNE_TEMPLATE_ARGS, {}},
        // section 0A item 33 [RQ-AKM-024]
        {"Set User Tune Template", 0x0A, 0x33, ItemKind::Set, item_data::PROGRAM_SET_USER_TUNE_TEMPLATE_ARGS, {}},
        // section 0A item 34 [RQ-AKM-024]
        {"Set Key", 0x0A, 0x34, ItemKind::Set, item_data::PROGRAM_SET_KEY_ARGS, {}},
        // section 0A item 38 [RQ-AKM-024]
        {"Get Semitone Tune", 0x0A, 0x38, ItemKind::Get, {}, item_data::PROGRAM_GET_SEMITONE_TUNE_REPLY},
        // section 0A item 39 [RQ-AKM-024]
        {"Get Fine Tune", 0x0A, 0x39, ItemKind::Get, {}, item_data::PROGRAM_GET_FINE_TUNE_REPLY},
        // section 0A item 3A [RQ-AKM-024]
        {"Get Tune Template", 0x0A, 0x3A, ItemKind::Get, {}, item_data::PROGRAM_GET_TUNE_TEMPLATE_REPLY},
        // section 0A item 3B [RQ-AKM-024]
        {"Get User Tune Template", 0x0A, 0x3B, ItemKind::Get, {}, item_data::PROGRAM_GET_USER_TUNE_TEMPLATE_REPLY},
        // section 0A item 3C [RQ-AKM-024]
        {"Get Key", 0x0A, 0x3C, ItemKind::Get, {}, item_data::PROGRAM_GET_KEY_REPLY},
        // section 0A item 40 [RQ-AKM-024]
        {"Set Pitch Bend Up", 0x0A, 0x40, ItemKind::Set, item_data::PROGRAM_SET_PITCH_BEND_UP_ARGS, {}},
        // section 0A item 41 [RQ-AKM-024]
        {"Set Pitch Bend Down", 0x0A, 0x41, ItemKind::Set, item_data::PROGRAM_SET_PITCH_BEND_DOWN_ARGS, {}},
        // section 0A item 42 [RQ-AKM-024]
        {"Set Bend Mode", 0x0A, 0x42, ItemKind::Set, item_data::PROGRAM_SET_BEND_MODE_ARGS, {}},
        // section 0A item 43 [RQ-AKM-024]
        {"Set Aftertouch Value", 0x0A, 0x43, ItemKind::Set, item_data::PROGRAM_SET_AFTERTOUCH_VALUE_ARGS, {}},
        // section 0A item 44 [RQ-AKM-024]
        {"Set Legato Setting", 0x0A, 0x44, ItemKind::Set, item_data::PROGRAM_SET_LEGATO_ARGS, {}},
        // section 0A item 45 [RQ-AKM-024]
        {"Set Portamento Enable", 0x0A, 0x45, ItemKind::Set, item_data::PROGRAM_SET_PORTAMENTO_ENABLE_ARGS, {}},
        // section 0A item 46 [RQ-AKM-024]
        {"Set Portamento Mode", 0x0A, 0x46, ItemKind::Set, item_data::PROGRAM_SET_PORTAMENTO_MODE_ARGS, {}},
        // section 0A item 47 [RQ-AKM-024]
        {"Set Portamento Time", 0x0A, 0x47, ItemKind::Set, item_data::PROGRAM_SET_PORTAMENTO_TIME_ARGS, {}},
        // section 0A item 48 [RQ-AKM-024]
        {"Get Pitch Bend Up", 0x0A, 0x48, ItemKind::Get, {}, item_data::PROGRAM_GET_PITCH_BEND_UP_REPLY},
        // section 0A item 49 [RQ-AKM-024]
        {"Get Pitch Bend Down", 0x0A, 0x49, ItemKind::Get, {}, item_data::PROGRAM_GET_PITCH_BEND_DOWN_REPLY},
        // section 0A item 4A [RQ-AKM-024]
        {"Get Bend Mode", 0x0A, 0x4A, ItemKind::Get, {}, item_data::PROGRAM_GET_BEND_MODE_REPLY},
        // section 0A item 4B [RQ-AKM-024]
        {"Get Aftertouch Value", 0x0A, 0x4B, ItemKind::Get, {}, item_data::PROGRAM_GET_AFTERTOUCH_VALUE_REPLY},
        // section 0A item 4C [RQ-AKM-024]
        {"Get Legato Setting", 0x0A, 0x4C, ItemKind::Get, {}, item_data::PROGRAM_GET_LEGATO_REPLY},
        // section 0A item 4D [RQ-AKM-024]
        {"Get Portamento Enable", 0x0A, 0x4D, ItemKind::Get, {}, item_data::PROGRAM_GET_PORTAMENTO_ENABLE_REPLY},
        // section 0A item 4E [RQ-AKM-024]
        {"Get Portamento Mode", 0x0A, 0x4E, ItemKind::Get, {}, item_data::PROGRAM_GET_PORTAMENTO_MODE_REPLY},
        // section 0A item 4F [RQ-AKM-024]
        {"Get Portamento Time", 0x0A, 0x4F, ItemKind::Get, {}, item_data::PROGRAM_GET_PORTAMENTO_TIME_REPLY},
        // section 0A item 50 [RQ-AKM-024]
        {"Set LFO Rate", 0x0A, 0x50, ItemKind::Set, item_data::PROGRAM_SET_LFO_RATE_ARGS, {}},
        // section 0A item 51 [RQ-AKM-024]
        {"Set LFO Delay", 0x0A, 0x51, ItemKind::Set, item_data::PROGRAM_SET_LFO_DELAY_ARGS, {}},
        // section 0A item 52 [RQ-AKM-024]
        {"Set LFO Depth", 0x0A, 0x52, ItemKind::Set, item_data::PROGRAM_SET_LFO_DEPTH_ARGS, {}},
        // section 0A item 53 [RQ-AKM-024]
        {"Set LFO Waveform", 0x0A, 0x53, ItemKind::Set, item_data::PROGRAM_SET_LFO_WAVEFORM_ARGS, {}},
        // section 0A item 54 [RQ-AKM-024]
        {"Set LFO Sync", 0x0A, 0x54, ItemKind::Set, item_data::PROGRAM_SET_LFO_SYNC_ARGS, {}},
        // section 0A item 55 [RQ-AKM-024]
        {"Set LFO Re-trigger", 0x0A, 0x55, ItemKind::Set, item_data::PROGRAM_SET_LFO_RETRIGGER_ARGS, {}},
        // section 0A item 56 [RQ-AKM-024]
        {"Set LFO Rate Mod Source", 0x0A, 0x56, ItemKind::Set, item_data::PROGRAM_SET_LFO_RATE_MOD_SOURCE_ARGS, {}},
        // section 0A item 57 [RQ-AKM-024]
        {"Set LFO Rate Mod Value", 0x0A, 0x57, ItemKind::Set, item_data::PROGRAM_SET_LFO_RATE_MOD_VALUE_ARGS, {}},
        // section 0A item 58 [RQ-AKM-024]
        {"Set LFO Delay Mod Source", 0x0A, 0x58, ItemKind::Set, item_data::PROGRAM_SET_LFO_DELAY_MOD_SOURCE_ARGS, {}},
        // section 0A item 59 [RQ-AKM-024]
        {"Set LFO Delay Mod Value", 0x0A, 0x59, ItemKind::Set, item_data::PROGRAM_SET_LFO_DELAY_MOD_VALUE_ARGS, {}},
        // section 0A item 5A [RQ-AKM-024]
        {"Set LFO Depth Mod Source", 0x0A, 0x5A, ItemKind::Set, item_data::PROGRAM_SET_LFO_DEPTH_MOD_SOURCE_ARGS, {}},
        // section 0A item 5B [RQ-AKM-024]
        {"Set LFO Depth Mod Value", 0x0A, 0x5B, ItemKind::Set, item_data::PROGRAM_SET_LFO_DEPTH_MOD_VALUE_ARGS, {}},
        // section 0A item 5C [RQ-AKM-024]
        {"Set LFO Modwheel", 0x0A, 0x5C, ItemKind::Set, item_data::PROGRAM_SET_LFO_MODWHEEL_ARGS, {}},
        // section 0A item 5D [RQ-AKM-024]
        {"Set LFO Aftertouch", 0x0A, 0x5D, ItemKind::Set, item_data::PROGRAM_SET_LFO_AFTERTOUCH_ARGS, {}},
        // section 0A item 5E [RQ-AKM-024]
        {"Set LFO MIDI Clock Sync Enable", 0x0A, 0x5E, ItemKind::Set, item_data::PROGRAM_SET_LFO_MIDI_CLOCK_SYNC_ENABLE_ARGS, {}},
        // section 0A item 5F [RQ-AKM-024]
        {"Set LFO MIDI Clock Sync Division", 0x0A, 0x5F, ItemKind::Set, item_data::PROGRAM_SET_LFO_MIDI_CLOCK_SYNC_DIVISION_ARGS, {}},
        // section 0A item 60 [RQ-AKM-024]
        {"Get LFO Rate", 0x0A, 0x60, ItemKind::Get, item_data::PROGRAM_GET_LFO_RATE_ARGS, item_data::PROGRAM_GET_LFO_RATE_REPLY},
        // section 0A item 61 [RQ-AKM-024]
        {"Get LFO Delay", 0x0A, 0x61, ItemKind::Get, item_data::PROGRAM_GET_LFO_DELAY_ARGS, item_data::PROGRAM_GET_LFO_DELAY_REPLY},
        // section 0A item 62 [RQ-AKM-024]
        {"Get LFO Depth", 0x0A, 0x62, ItemKind::Get, item_data::PROGRAM_GET_LFO_DEPTH_ARGS, item_data::PROGRAM_GET_LFO_DEPTH_REPLY},
        // section 0A item 63 [RQ-AKM-024]
        {"Get LFO Waveform", 0x0A, 0x63, ItemKind::Get, item_data::PROGRAM_GET_LFO_WAVEFORM_ARGS, item_data::PROGRAM_GET_LFO_WAVEFORM_REPLY},
        // section 0A item 64 [RQ-AKM-024]
        {"Get LFO Sync", 0x0A, 0x64, ItemKind::Get, item_data::PROGRAM_GET_LFO_SYNC_ARGS, item_data::PROGRAM_GET_LFO_SYNC_REPLY},
        // section 0A item 65 [RQ-AKM-024]
        {"Get LFO Re-trigger", 0x0A, 0x65, ItemKind::Get, item_data::PROGRAM_GET_LFO_RETRIGGER_ARGS, item_data::PROGRAM_GET_LFO_RETRIGGER_REPLY},
        // section 0A item 66 [RQ-AKM-024]
        {"Get LFO Rate Mod Source", 0x0A, 0x66, ItemKind::Get, item_data::PROGRAM_GET_LFO_RATE_MOD_SOURCE_ARGS, item_data::PROGRAM_GET_LFO_RATE_MOD_SOURCE_REPLY},
        // section 0A item 67 [RQ-AKM-024]
        {"Get LFO Rate Mod Value", 0x0A, 0x67, ItemKind::Get, item_data::PROGRAM_GET_LFO_RATE_MOD_VALUE_ARGS, item_data::PROGRAM_GET_LFO_RATE_MOD_VALUE_REPLY},
        // section 0A item 68 [RQ-AKM-024]
        {"Get LFO Delay Mod Source", 0x0A, 0x68, ItemKind::Get, item_data::PROGRAM_GET_LFO_DELAY_MOD_SOURCE_ARGS, item_data::PROGRAM_GET_LFO_DELAY_MOD_SOURCE_REPLY},
        // section 0A item 69 [RQ-AKM-024]
        {"Get LFO Delay Mod Value", 0x0A, 0x69, ItemKind::Get, item_data::PROGRAM_GET_LFO_DELAY_MOD_VALUE_ARGS, item_data::PROGRAM_GET_LFO_DELAY_MOD_VALUE_REPLY},
        // section 0A item 6A [RQ-AKM-024]
        {"Get LFO Depth Mod Source", 0x0A, 0x6A, ItemKind::Get, item_data::PROGRAM_GET_LFO_DEPTH_MOD_SOURCE_ARGS, item_data::PROGRAM_GET_LFO_DEPTH_MOD_SOURCE_REPLY},
        // section 0A item 6B [RQ-AKM-024]
        {"Get LFO Depth Mod Value", 0x0A, 0x6B, ItemKind::Get, item_data::PROGRAM_GET_LFO_DEPTH_MOD_VALUE_ARGS, item_data::PROGRAM_GET_LFO_DEPTH_MOD_VALUE_REPLY},
        // section 0A item 6C [RQ-AKM-024]
        {"Get LFO Modwheel", 0x0A, 0x6C, ItemKind::Get, item_data::PROGRAM_GET_LFO_MODWHEEL_ARGS, item_data::PROGRAM_GET_LFO_MODWHEEL_REPLY},
        // section 0A item 6D [RQ-AKM-024]
        {"Get LFO Aftertouch", 0x0A, 0x6D, ItemKind::Get, item_data::PROGRAM_GET_LFO_AFTERTOUCH_ARGS, item_data::PROGRAM_GET_LFO_AFTERTOUCH_REPLY},
        // section 0A item 6E [RQ-AKM-024]
        {"Get LFO MIDI Clock Sync Enable", 0x0A, 0x6E, ItemKind::Get, item_data::PROGRAM_GET_LFO_MIDI_CLOCK_SYNC_ENABLE_ARGS, item_data::PROGRAM_GET_LFO_MIDI_CLOCK_SYNC_ENABLE_REPLY},
        // section 0A item 6F [RQ-AKM-024]
        {"Get LFO MIDI Clock Sync Division", 0x0A, 0x6F, ItemKind::Get, item_data::PROGRAM_GET_LFO_MIDI_CLOCK_SYNC_DIVISION_ARGS, item_data::PROGRAM_GET_LFO_MIDI_CLOCK_SYNC_DIVISION_REPLY},
        // section 0A item 70 [RQ-AKM-024]
        {"Set Pitch Mod Source", 0x0A, 0x70, ItemKind::Set, item_data::PROGRAM_SET_PITCH_MOD_SOURCE_ARGS, {}},
        // section 0A item 71 [RQ-AKM-024]
        {"Set Amp Mod Source (Keygroup Modulation Sources)", 0x0A, 0x71, ItemKind::Set, item_data::PROGRAM_SET_KEYGROUP_AMP_MOD_SOURCE_ARGS, {}},
        // section 0A item 72 [RQ-AKM-024]
        {"Set Filter Mod Input Source", 0x0A, 0x72, ItemKind::Set, item_data::PROGRAM_SET_FILTER_MOD_INPUT_SOURCE_ARGS, {}},
        // section 0A item 74 [RQ-AKM-024]
        {"Get Pitch Mod Source", 0x0A, 0x74, ItemKind::Get, item_data::PROGRAM_GET_PITCH_MOD_SOURCE_ARGS, item_data::PROGRAM_GET_PITCH_MOD_SOURCE_REPLY},
        // section 0A item 75 [RQ-AKM-024]
        {"Get Amp Mod Source (Keygroup Modulation Sources)", 0x0A, 0x75, ItemKind::Get, item_data::PROGRAM_GET_KEYGROUP_AMP_MOD_SOURCE_ARGS, item_data::PROGRAM_GET_KEYGROUP_AMP_MOD_SOURCE_REPLY},
        // section 0A item 76 [RQ-AKM-024]
        {"Get Filter Mod Input Source", 0x0A, 0x76, ItemKind::Get, item_data::PROGRAM_GET_FILTER_MOD_INPUT_SOURCE_ARGS, item_data::PROGRAM_GET_FILTER_MOD_INPUT_SOURCE_REPLY},
        // section 0A item 0A [RQ-AKM-022]
        {"Set Program Number", 0x0A, 0x0A, ItemKind::Set, item_data::PROGRAM_SET_NUMBER_ARGS, {}},
        // section 0A item 0B [RQ-AKM-022]
        {"Add Keygroups to Program", 0x0A, 0x0B, ItemKind::Set, item_data::PROGRAM_ADD_KEYGROUPS_ARGS, {}},
        // section 0A item 0C [RQ-AKM-022]
        {"Delete Keygroup from Program", 0x0A, 0x0C, ItemKind::Set, item_data::PROGRAM_DELETE_KEYGROUP_ARGS, {}},
        // section 0A item 0D [RQ-AKM-022]
        {"Set Keygroup Crossfade", 0x0A, 0x0D, ItemKind::Set, item_data::PROGRAM_SET_CROSSFADE_ARGS, {}},
        // section 0A item 11 [RQ-AKM-022, RQ-AKM-023]
        {"Get Current Program's Program Number", 0x0A, 0x11, ItemKind::Get, {}, item_data::PROGRAM_GET_NUMBER_REPLY},
        // section 0A item 14 [RQ-AKM-022, RQ-AKM-023]
        {"Get Number of Keygroups in Current Program", 0x0A, 0x14, ItemKind::Get, {}, item_data::PROGRAM_GET_KEYGROUP_COUNT_REPLY},
        // section 0A item 15 [RQ-AKM-022, RQ-AKM-023]
        {"Get Keygroup Crossfade", 0x0A, 0x15, ItemKind::Get, {}, item_data::PROGRAM_GET_CROSSFADE_REPLY},
        // section 0A item 12 [RQ-AKM-023]
        {"Get Current Program Index", 0x0A, 0x12, ItemKind::Get, {}, item_data::PROGRAM_GET_INDEX_REPLY},
        // section 0A item 18 [RQ-AKM-023]
        {"Get the Program Numbers of all Programs in memory", 0x0A, 0x18, ItemKind::Get, {}, item_data::PROGRAM_GET_ALL_NUMBERS_REPLY},
        // section 0A item 19 [RQ-AKM-023]
        {"Get the names of all Programs in memory", 0x0A, 0x19, ItemKind::Get, {}, item_data::PROGRAM_GET_ALL_NAMES_REPLY},
        // section 0A item 07 [RQ-AKM-025]
        {"Delete ALL programs from memory", 0x0A, 0x07, ItemKind::Set, {}, {}},
        // section 08 item 01 [RQ-AKM-028]
        {"Select Keygroup", 0x08, 0x01, ItemKind::Set, item_data::KEYGROUP_SELECT_ARGS, {}},
        // section 08 item 02 [RQ-AKM-028]
        {"Get current Keygroup", 0x08, 0x02, ItemKind::Get, {}, item_data::KEYGROUP_GET_CURRENT_REPLY},
        // section 08 item 04 [RQ-AKM-029]
        {"Set Low Note", 0x08, 0x04, ItemKind::Set, item_data::KEYGROUP_SET_LOW_NOTE_ARGS, {}},
        // section 08 item 05 [RQ-AKM-029]
        {"Set High Note", 0x08, 0x05, ItemKind::Set, item_data::KEYGROUP_SET_HIGH_NOTE_ARGS, {}},
        // section 08 item 06 [RQ-AKM-029]
        {"Set Mute Group", 0x08, 0x06, ItemKind::Set, item_data::KEYGROUP_SET_MUTE_GROUP_ARGS, {}},
        // section 08 item 07 [RQ-AKM-029]
        {"Set FX override", 0x08, 0x07, ItemKind::Set, item_data::KEYGROUP_SET_FX_OVERRIDE_ARGS, {}},
        // section 08 item 08 [RQ-AKM-029]
        {"Set FX Send Level", 0x08, 0x08, ItemKind::Set, item_data::KEYGROUP_SET_FX_SEND_LEVEL_ARGS, {}},
        // section 08 item 09 [RQ-AKM-029]
        {"Set Zone Crossfade", 0x08, 0x09, ItemKind::Set, item_data::KEYGROUP_SET_ZONE_CROSSFADE_ARGS, {}},
        // section 08 item 0A [RQ-AKM-029]
        {"Get Low Note", 0x08, 0x0A, ItemKind::Get, {}, item_data::KEYGROUP_GET_LOW_NOTE_REPLY},
        // section 08 item 0B [RQ-AKM-029]
        {"Get High Note", 0x08, 0x0B, ItemKind::Get, {}, item_data::KEYGROUP_GET_HIGH_NOTE_REPLY},
        // section 08 item 0C [RQ-AKM-029]
        {"Get Mute Group", 0x08, 0x0C, ItemKind::Get, {}, item_data::KEYGROUP_GET_MUTE_GROUP_REPLY},
        // section 08 item 0D [RQ-AKM-029]
        {"Get FX override", 0x08, 0x0D, ItemKind::Get, {}, item_data::KEYGROUP_GET_FX_OVERRIDE_REPLY},
        // section 08 item 0E [RQ-AKM-029]
        {"Get FX Send Level", 0x08, 0x0E, ItemKind::Get, {}, item_data::KEYGROUP_GET_FX_SEND_LEVEL_REPLY},
        // section 08 item 0F [RQ-AKM-029]
        {"Get Zone Crossfade", 0x08, 0x0F, ItemKind::Get, {}, item_data::KEYGROUP_GET_ZONE_CROSSFADE_REPLY},
        // section 08 item 10 [RQ-AKM-030]
        {"Set Semitone Tune", 0x08, 0x10, ItemKind::Set, item_data::KEYGROUP_SET_SEMITONE_TUNE_ARGS, {}},
        // section 08 item 11 [RQ-AKM-030]
        {"Set Fine Tune", 0x08, 0x11, ItemKind::Set, item_data::KEYGROUP_SET_FINE_TUNE_ARGS, {}},
        // section 08 item 12 [RQ-AKM-030]
        {"Set Keygroup Level", 0x08, 0x12, ItemKind::Set, item_data::KEYGROUP_SET_LEVEL_ARGS, {}},
        // section 08 item 13 [RQ-AKM-030]
        {"Set Pitch Mod Value", 0x08, 0x13, ItemKind::Set, item_data::KEYGROUP_SET_PITCH_MOD_VALUE_ARGS, {}},
        // section 08 item 14 [RQ-AKM-030]
        {"Set Amp Mod Value", 0x08, 0x14, ItemKind::Set, item_data::KEYGROUP_SET_AMP_MOD_VALUE_ARGS, {}},
        // section 08 item 18 [RQ-AKM-030]
        {"Get Semitone Tune", 0x08, 0x18, ItemKind::Get, {}, item_data::KEYGROUP_GET_SEMITONE_TUNE_REPLY},
        // section 08 item 19 [RQ-AKM-030]
        {"Get Fine Tune", 0x08, 0x19, ItemKind::Get, {}, item_data::KEYGROUP_GET_FINE_TUNE_REPLY},
        // section 08 item 1A [RQ-AKM-030]
        {"Get Keygroup Level", 0x08, 0x1A, ItemKind::Get, {}, item_data::KEYGROUP_GET_LEVEL_REPLY},
        // section 08 item 1B [RQ-AKM-030]
        {"Get Pitch Mod Value", 0x08, 0x1B, ItemKind::Get, item_data::KEYGROUP_GET_PITCH_MOD_VALUE_ARGS, item_data::KEYGROUP_GET_PITCH_MOD_VALUE_REPLY},
        // section 08 item 1C [RQ-AKM-030]
        {"Get Amp Mod Value", 0x08, 0x1C, ItemKind::Get, item_data::KEYGROUP_GET_AMP_MOD_VALUE_ARGS, item_data::KEYGROUP_GET_AMP_MOD_VALUE_REPLY},
        // section 08 item 20 [RQ-AKM-030]
        {"Set Filter Mode", 0x08, 0x20, ItemKind::Set, item_data::KEYGROUP_SET_FILTER_MODE_ARGS, {}},
        // section 08 item 21 [RQ-AKM-030]
        {"Set Filter Cutoff Frequency", 0x08, 0x21, ItemKind::Set, item_data::KEYGROUP_SET_FILTER_CUTOFF_ARGS, {}},
        // section 08 item 22 [RQ-AKM-030]
        {"Set Filter Resonance", 0x08, 0x22, ItemKind::Set, item_data::KEYGROUP_SET_FILTER_RESONANCE_ARGS, {}},
        // section 08 item 23 [RQ-AKM-030]
        {"Set Filter Keyboard Track", 0x08, 0x23, ItemKind::Set, item_data::KEYGROUP_SET_FILTER_KEYBOARD_TRACK_ARGS, {}},
        // section 08 item 24 [RQ-AKM-030]
        {"Set Filter Mod Input Value", 0x08, 0x24, ItemKind::Set, item_data::KEYGROUP_SET_FILTER_MOD_INPUT_VALUE_ARGS, {}},
        // section 08 item 25 [RQ-AKM-030]
        {"Set Filter Attenuation", 0x08, 0x25, ItemKind::Set, item_data::KEYGROUP_SET_FILTER_ATTENUATION_ARGS, {}},
        // section 08 item 28 [RQ-AKM-030]
        {"Get Filter Mode", 0x08, 0x28, ItemKind::Get, {}, item_data::KEYGROUP_GET_FILTER_MODE_REPLY},
        // section 08 item 29 [RQ-AKM-030]
        {"Get Filter Cutoff Frequency", 0x08, 0x29, ItemKind::Get, {}, item_data::KEYGROUP_GET_FILTER_CUTOFF_REPLY},
        // section 08 item 2A [RQ-AKM-030]
        {"Get Filter Resonance", 0x08, 0x2A, ItemKind::Get, {}, item_data::KEYGROUP_GET_FILTER_RESONANCE_REPLY},
        // section 08 item 2B [RQ-AKM-030]
        {"Get Filter Keyboard Track", 0x08, 0x2B, ItemKind::Get, {}, item_data::KEYGROUP_GET_FILTER_KEYBOARD_TRACK_REPLY},
        // section 08 item 2C [RQ-AKM-030]
        {"Get Filter Mod Input Value", 0x08, 0x2C, ItemKind::Get, item_data::KEYGROUP_GET_FILTER_MOD_INPUT_VALUE_ARGS, item_data::KEYGROUP_GET_FILTER_MOD_INPUT_VALUE_REPLY},
        // section 08 item 2D [RQ-AKM-030]
        {"Get Filter Attenuation", 0x08, 0x2D, ItemKind::Get, {}, item_data::KEYGROUP_GET_FILTER_ATTENUATION_REPLY},
        // section 08 item 30 [RQ-AKM-030]
        {"Set Filter Envelope Attack", 0x08, 0x30, ItemKind::Set, item_data::KEYGROUP_SET_FILTER_ENV_ATTACK_ARGS, {}},
        // section 08 item 31 [RQ-AKM-030]
        {"Set Filter Envelope Velocity->Attack", 0x08, 0x31, ItemKind::Set, item_data::KEYGROUP_SET_FILTER_ENV_VELOCITY_TO_ATTACK_ARGS, {}},
        // section 08 item 32 [RQ-AKM-030]
        {"Set Filter Envelope Decay", 0x08, 0x32, ItemKind::Set, item_data::KEYGROUP_SET_FILTER_ENV_DECAY_ARGS, {}},
        // section 08 item 33 [RQ-AKM-030]
        {"Set Filter Envelope Sustain", 0x08, 0x33, ItemKind::Set, item_data::KEYGROUP_SET_FILTER_ENV_SUSTAIN_ARGS, {}},
        // section 08 item 34 [RQ-AKM-030]
        {"Set Filter Envelope Release", 0x08, 0x34, ItemKind::Set, item_data::KEYGROUP_SET_FILTER_ENV_RELEASE_ARGS, {}},
        // section 08 item 35 [RQ-AKM-030]
        {"Set Filter Envelope On Velocity->Release", 0x08, 0x35, ItemKind::Set, item_data::KEYGROUP_SET_FILTER_ENV_ON_VELOCITY_TO_RELEASE_ARGS, {}},
        // section 08 item 36 [RQ-AKM-030]
        {"Set Filter Envelope Keyscale", 0x08, 0x36, ItemKind::Set, item_data::KEYGROUP_SET_FILTER_ENV_KEYSCALE_ARGS, {}},
        // section 08 item 37 [RQ-AKM-030]
        {"Set Filter Envelope Depth", 0x08, 0x37, ItemKind::Set, item_data::KEYGROUP_SET_FILTER_ENV_DEPTH_ARGS, {}},
        // section 08 item 38 [RQ-AKM-030, RQ-AKM-032]
        {"Set Filter Envelope Off Velocity->Release", 0x08, 0x38, ItemKind::Set, item_data::KEYGROUP_SET_FILTER_ENV_OFF_VELOCITY_TO_RELEASE_ARGS, {}},
        // section 08 item 40 [RQ-AKM-030]
        {"Get Filter Envelope Attack", 0x08, 0x40, ItemKind::Get, {}, item_data::KEYGROUP_GET_FILTER_ENV_ATTACK_REPLY},
        // section 08 item 41 [RQ-AKM-030]
        {"Get Filter Envelope Velocity->Attack", 0x08, 0x41, ItemKind::Get, {}, item_data::KEYGROUP_GET_FILTER_ENV_VELOCITY_TO_ATTACK_REPLY},
        // section 08 item 42 [RQ-AKM-030]
        {"Get Filter Envelope Decay", 0x08, 0x42, ItemKind::Get, {}, item_data::KEYGROUP_GET_FILTER_ENV_DECAY_REPLY},
        // section 08 item 43 [RQ-AKM-030]
        {"Get Filter Envelope Sustain", 0x08, 0x43, ItemKind::Get, {}, item_data::KEYGROUP_GET_FILTER_ENV_SUSTAIN_REPLY},
        // section 08 item 44 [RQ-AKM-030]
        {"Get Filter Envelope Release", 0x08, 0x44, ItemKind::Get, {}, item_data::KEYGROUP_GET_FILTER_ENV_RELEASE_REPLY},
        // section 08 item 45 [RQ-AKM-030]
        {"Get Filter Envelope On Velocity->Release", 0x08, 0x45, ItemKind::Get, {}, item_data::KEYGROUP_GET_FILTER_ENV_ON_VELOCITY_TO_RELEASE_REPLY},
        // section 08 item 46 [RQ-AKM-030]
        {"Get Filter Envelope Keyscale", 0x08, 0x46, ItemKind::Get, {}, item_data::KEYGROUP_GET_FILTER_ENV_KEYSCALE_REPLY},
        // section 08 item 47 [RQ-AKM-030]
        {"Get Filter Envelope Depth", 0x08, 0x47, ItemKind::Get, {}, item_data::KEYGROUP_GET_FILTER_ENV_DEPTH_REPLY},
        // section 08 item 48 [RQ-AKM-030, RQ-AKM-032]
        {"Get Filter Envelope Off Velocity->Release", 0x08, 0x48, ItemKind::Get, {}, item_data::KEYGROUP_GET_FILTER_ENV_OFF_VELOCITY_TO_RELEASE_REPLY},
        // section 08 item 50 [RQ-AKM-030]
        {"Set Amplitude Envelope Attack", 0x08, 0x50, ItemKind::Set, item_data::KEYGROUP_SET_AMP_ENV_ATTACK_ARGS, {}},
        // section 08 item 51 [RQ-AKM-030]
        {"Set Amplitude Envelope Velocity->Attack", 0x08, 0x51, ItemKind::Set, item_data::KEYGROUP_SET_AMP_ENV_VELOCITY_TO_ATTACK_ARGS, {}},
        // section 08 item 52 [RQ-AKM-030]
        {"Set Amplitude Envelope Decay", 0x08, 0x52, ItemKind::Set, item_data::KEYGROUP_SET_AMP_ENV_DECAY_ARGS, {}},
        // section 08 item 53 [RQ-AKM-030]
        {"Set Amplitude Envelope Sustain", 0x08, 0x53, ItemKind::Set, item_data::KEYGROUP_SET_AMP_ENV_SUSTAIN_ARGS, {}},
        // section 08 item 54 [RQ-AKM-030]
        {"Set Amplitude Envelope Release", 0x08, 0x54, ItemKind::Set, item_data::KEYGROUP_SET_AMP_ENV_RELEASE_ARGS, {}},
        // section 08 item 55 [RQ-AKM-030]
        {"Set Amplitude Envelope On Velocity->Release", 0x08, 0x55, ItemKind::Set, item_data::KEYGROUP_SET_AMP_ENV_ON_VELOCITY_TO_RELEASE_ARGS, {}},
        // section 08 item 56 [RQ-AKM-030]
        {"Set Amplitude Envelope Keyscale", 0x08, 0x56, ItemKind::Set, item_data::KEYGROUP_SET_AMP_ENV_KEYSCALE_ARGS, {}},
        // section 08 item 57 [RQ-AKM-030, RQ-AKM-032]
        {"Set Amplitude Envelope Off Velocity->Release", 0x08, 0x57, ItemKind::Set, item_data::KEYGROUP_SET_AMP_ENV_OFF_VELOCITY_TO_RELEASE_ARGS, {}},
        // section 08 item 58 [RQ-AKM-030]
        {"Get Amplitude Envelope Attack", 0x08, 0x58, ItemKind::Get, {}, item_data::KEYGROUP_GET_AMP_ENV_ATTACK_REPLY},
        // section 08 item 59 [RQ-AKM-030]
        {"Get Amplitude Envelope Velocity->Attack", 0x08, 0x59, ItemKind::Get, {}, item_data::KEYGROUP_GET_AMP_ENV_VELOCITY_TO_ATTACK_REPLY},
        // section 08 item 5A [RQ-AKM-030]
        {"Get Amplitude Envelope Decay", 0x08, 0x5A, ItemKind::Get, {}, item_data::KEYGROUP_GET_AMP_ENV_DECAY_REPLY},
        // section 08 item 5B [RQ-AKM-030]
        {"Get Amplitude Envelope Sustain", 0x08, 0x5B, ItemKind::Get, {}, item_data::KEYGROUP_GET_AMP_ENV_SUSTAIN_REPLY},
        // section 08 item 5C [RQ-AKM-030]
        {"Get Amplitude Envelope Release", 0x08, 0x5C, ItemKind::Get, {}, item_data::KEYGROUP_GET_AMP_ENV_RELEASE_REPLY},
        // section 08 item 5D [RQ-AKM-030]
        {"Get Amplitude Envelope On Velocity->Release", 0x08, 0x5D, ItemKind::Get, {}, item_data::KEYGROUP_GET_AMP_ENV_ON_VELOCITY_TO_RELEASE_REPLY},
        // section 08 item 5E [RQ-AKM-030]
        {"Get Amplitude Envelope Keyscale", 0x08, 0x5E, ItemKind::Get, {}, item_data::KEYGROUP_GET_AMP_ENV_KEYSCALE_REPLY},
        // section 08 item 5F [RQ-AKM-030, RQ-AKM-032]
        {"Get Amplitude Envelope Off Velocity->Release", 0x08, 0x5F, ItemKind::Get, {}, item_data::KEYGROUP_GET_AMP_ENV_OFF_VELOCITY_TO_RELEASE_REPLY},
        // section 08 item 60 [RQ-AKM-030]
        {"Set Aux Env. Rate", 0x08, 0x60, ItemKind::Set, item_data::KEYGROUP_SET_AUX_ENV_RATE_ARGS, {}},
        // section 08 item 61 [RQ-AKM-030]
        {"Set Aux Env. Velocity->Rate", 0x08, 0x61, ItemKind::Set, item_data::KEYGROUP_SET_AUX_ENV_VELOCITY_TO_RATE_ARGS, {}},
        // section 08 item 62 [RQ-AKM-030]
        {"Set Aux Env. Keyboard->R2/R4", 0x08, 0x62, ItemKind::Set, item_data::KEYGROUP_SET_AUX_ENV_KEYBOARD_TO_R2_R4_ARGS, {}},
        // section 08 item 63 [RQ-AKM-030]
        {"Set Aux Env. Level", 0x08, 0x63, ItemKind::Set, item_data::KEYGROUP_SET_AUX_ENV_LEVEL_ARGS, {}},
        // section 08 item 64 [RQ-AKM-030, RQ-AKM-032]
        {"Set Aux Env. Off Velocity->Rate (Aux Rate 4 only)", 0x08, 0x64, ItemKind::Set, item_data::KEYGROUP_SET_AUX_ENV_OFF_VELOCITY_TO_RATE_ARGS, {}},
        // section 08 item 68 [RQ-AKM-030]
        {"Get Aux Env. Rate", 0x08, 0x68, ItemKind::Get, item_data::KEYGROUP_GET_AUX_ENV_RATE_ARGS, item_data::KEYGROUP_GET_AUX_ENV_RATE_REPLY},
        // section 08 item 69 [RQ-AKM-030]
        {"Get Aux Env. Velocity->Rate", 0x08, 0x69, ItemKind::Get, item_data::KEYGROUP_GET_AUX_ENV_VELOCITY_TO_RATE_ARGS, item_data::KEYGROUP_GET_AUX_ENV_VELOCITY_TO_RATE_REPLY},
        // section 08 item 6A [RQ-AKM-030]
        {"Get Aux Env. Keyboard->R2/R4", 0x08, 0x6A, ItemKind::Get, {}, item_data::KEYGROUP_GET_AUX_ENV_KEYBOARD_TO_R2_R4_REPLY},
        // section 08 item 6B [RQ-AKM-030]
        {"Get Aux Env. Level", 0x08, 0x6B, ItemKind::Get, item_data::KEYGROUP_GET_AUX_ENV_LEVEL_ARGS, item_data::KEYGROUP_GET_AUX_ENV_LEVEL_REPLY},
        // section 08 item 6C [RQ-AKM-030, RQ-AKM-032]
        {"Get Aux Env. Off Velocity->Rate (Aux Rate 4 only)", 0x08, 0x6C, ItemKind::Get, item_data::KEYGROUP_GET_AUX_ENV_OFF_VELOCITY_TO_RATE_ARGS, item_data::KEYGROUP_GET_AUX_ENV_OFF_VELOCITY_TO_RATE_REPLY},
        // section 06 item 01 [RQ-AKM-035]
        {"Set Zone Sample", 0x06, 0x01, ItemKind::Set, item_data::ZONE_SET_SAMPLE_ARGS, {}},
        // section 06 item 02 [RQ-AKM-034]
        {"Set Zone Level", 0x06, 0x02, ItemKind::Set, item_data::ZONE_SET_LEVEL_ARGS, {}},
        // section 06 item 03 [RQ-AKM-034]
        {"Set Zone Pan/Balance", 0x06, 0x03, ItemKind::Set, item_data::ZONE_SET_PAN_BALANCE_ARGS, {}},
        // section 06 item 04 [RQ-AKM-034]
        {"Set Zone Output", 0x06, 0x04, ItemKind::Set, item_data::ZONE_SET_OUTPUT_ARGS, {}},
        // section 06 item 05 [RQ-AKM-034]
        {"Set Zone Filter", 0x06, 0x05, ItemKind::Set, item_data::ZONE_SET_FILTER_ARGS, {}},
        // section 06 item 06 [RQ-AKM-034]
        {"Set Zone Fine Tune", 0x06, 0x06, ItemKind::Set, item_data::ZONE_SET_FINE_TUNE_ARGS, {}},
        // section 06 item 07 [RQ-AKM-034]
        {"Set Zone Semitone Tune", 0x06, 0x07, ItemKind::Set, item_data::ZONE_SET_SEMITONE_TUNE_ARGS, {}},
        // section 06 item 08 [RQ-AKM-034]
        {"Set Zone Keyboard Track", 0x06, 0x08, ItemKind::Set, item_data::ZONE_SET_KEYBOARD_TRACK_ARGS, {}},
        // section 06 item 09 [RQ-AKM-034]
        {"Set Zone Playback", 0x06, 0x09, ItemKind::Set, item_data::ZONE_SET_PLAYBACK_ARGS, {}},
        // section 06 item 0A [RQ-AKM-034]
        {"Set Zone Velocity->Start", 0x06, 0x0A, ItemKind::Set, item_data::ZONE_SET_VELOCITY_TO_START_ARGS, {}},
        // section 06 item 0B [RQ-AKM-034]
        {"Set Zone High Velocity", 0x06, 0x0B, ItemKind::Set, item_data::ZONE_SET_HIGH_VELOCITY_ARGS, {}},
        // section 06 item 0C [RQ-AKM-034]
        {"Set Zone Low Velocity", 0x06, 0x0C, ItemKind::Set, item_data::ZONE_SET_LOW_VELOCITY_ARGS, {}},
        // section 06 item 0D [RQ-AKM-034]
        {"Set Zone Mute", 0x06, 0x0D, ItemKind::Set, item_data::ZONE_SET_MUTE_ARGS, {}},
        // section 06 item 0E [RQ-AKM-034]
        {"Set Zone Solo", 0x06, 0x0E, ItemKind::Set, item_data::ZONE_SET_SOLO_ARGS, {}},
        // section 06 item 21 [RQ-AKM-035]
        {"Get Zone Sample", 0x06, 0x21, ItemKind::Get, item_data::ZONE_GET_SAMPLE_ARGS, item_data::ZONE_GET_SAMPLE_REPLY},
        // section 06 item 22 [RQ-AKM-034]
        {"Get Zone Level", 0x06, 0x22, ItemKind::Get, item_data::ZONE_GET_LEVEL_ARGS, item_data::ZONE_GET_LEVEL_REPLY},
        // section 06 item 23 [RQ-AKM-034]
        {"Get Zone Pan/Balance", 0x06, 0x23, ItemKind::Get, item_data::ZONE_GET_PAN_BALANCE_ARGS, item_data::ZONE_GET_PAN_BALANCE_REPLY},
        // section 06 item 24 [RQ-AKM-034]
        {"Get Zone Output", 0x06, 0x24, ItemKind::Get, item_data::ZONE_GET_OUTPUT_ARGS, item_data::ZONE_GET_OUTPUT_REPLY},
        // section 06 item 25 [RQ-AKM-034]
        {"Get Zone Filter", 0x06, 0x25, ItemKind::Get, item_data::ZONE_GET_FILTER_ARGS, item_data::ZONE_GET_FILTER_REPLY},
        // section 06 item 26 [RQ-AKM-034]
        {"Get Zone Fine Tune", 0x06, 0x26, ItemKind::Get, item_data::ZONE_GET_FINE_TUNE_ARGS, item_data::ZONE_GET_FINE_TUNE_REPLY},
        // section 06 item 27 [RQ-AKM-034, RQ-AKM-037]
        {"Get Zone Semitone Tune", 0x06, 0x27, ItemKind::Get, item_data::ZONE_GET_SEMITONE_TUNE_ARGS, item_data::ZONE_GET_SEMITONE_TUNE_REPLY},
        // section 06 item 28 [RQ-AKM-034]
        {"Get Zone Keyboard Track", 0x06, 0x28, ItemKind::Get, item_data::ZONE_GET_KEYBOARD_TRACK_ARGS, item_data::ZONE_GET_KEYBOARD_TRACK_REPLY},
        // section 06 item 29 [RQ-AKM-034]
        {"Get Zone Playback", 0x06, 0x29, ItemKind::Get, item_data::ZONE_GET_PLAYBACK_ARGS, item_data::ZONE_GET_PLAYBACK_REPLY},
        // section 06 item 2A [RQ-AKM-034]
        {"Get Zone Velocity->Start", 0x06, 0x2A, ItemKind::Get, item_data::ZONE_GET_VELOCITY_TO_START_ARGS, item_data::ZONE_GET_VELOCITY_TO_START_REPLY},
        // section 06 item 2B [RQ-AKM-034]
        {"Get Zone High Velocity", 0x06, 0x2B, ItemKind::Get, item_data::ZONE_GET_HIGH_VELOCITY_ARGS, item_data::ZONE_GET_HIGH_VELOCITY_REPLY},
        // section 06 item 2C [RQ-AKM-034]
        {"Get Zone Low Velocity", 0x06, 0x2C, ItemKind::Get, item_data::ZONE_GET_LOW_VELOCITY_ARGS, item_data::ZONE_GET_LOW_VELOCITY_REPLY},
        // section 06 item 2D [RQ-AKM-034]
        {"Get Zone Mute", 0x06, 0x2D, ItemKind::Get, item_data::ZONE_GET_MUTE_ARGS, item_data::ZONE_GET_MUTE_REPLY},
        // section 06 item 2E [RQ-AKM-034]
        {"Get Zone Solo", 0x06, 0x2E, ItemKind::Get, item_data::ZONE_GET_SOLO_ARGS, item_data::ZONE_GET_SOLO_REPLY},
        // section 0E item 05 [RQ-AKM-045]
        {"Select Sample by name", 0x0E, 0x05, ItemKind::Set, item_data::SAMPLE_SELECT_BY_NAME_ARGS, {}},
        // section 0E item 06 [RQ-AKM-045]
        {"Select Sample by index", 0x0E, 0x06, ItemKind::Set, item_data::SAMPLE_SELECT_BY_INDEX_ARGS, {}},
        // section 0E item 08 [RQ-AKM-045]
        {"Delete the currently selected Sample", 0x0E, 0x08, ItemKind::Set, {}, {}},
        // section 0E item 09 [RQ-AKM-045]
        {"Rename the currently selected Sample", 0x0E, 0x09, ItemKind::Set, item_data::SAMPLE_RENAME_CURRENT_ARGS, {}},
        // section 0E item 0A [RQ-AKM-045]
        {"Start auditioning the current sample", 0x0E, 0x0A, ItemKind::Set, {}, {}},
        // section 0E item 0B [RQ-AKM-045]
        {"Stop auditioning the current sample", 0x0E, 0x0B, ItemKind::Set, {}, {}},
        // section 0E item 13 [RQ-AKM-045, RQ-AKM-047]
        {"Get Current Sample's Index", 0x0E, 0x13, ItemKind::Get, {}, item_data::SAMPLE_GET_CURRENT_INDEX_REPLY},
        // section 0E item 14 [RQ-AKM-045, RQ-AKM-047]
        {"Get Current Sample's Name", 0x0E, 0x14, ItemKind::Get, {}, item_data::SAMPLE_GET_CURRENT_NAME_REPLY},
        // section 0E item 07 [RQ-AKM-046]
        {"Delete ALL samples from memory", 0x0E, 0x07, ItemKind::Set, {}, {}},
    }};
}
